from __future__ import annotations

import logging

from sqlalchemy.engine import Engine


logger = logging.getLogger("sp2i-capex-api")


def ensure_powerbi_schema(engine: Engine) -> None:
    """
    Complete progressivement le schema PostgreSQL attendu par Power BI.

    `Base.metadata.create_all()` cree les tables manquantes, mais SQLAlchemy ne
    modifie pas automatiquement les tables deja existantes. Sur Render, une base
    peut donc contenir une ancienne version de `fact_metre` sans les colonnes
    analytiques (`capex_local`, `economie`, `lot_id`, etc.).

    Cette migration est volontairement idempotente :
    - elle ne supprime aucune table ;
    - elle n'efface aucune donnee ;
    - elle ajoute seulement les colonnes/dimensions manquantes ;
    - elle backfill les KPI a partir des colonnes historiques.
    """
    sql = """
    CREATE TABLE IF NOT EXISTS dim_projet (
        projet_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        projet_code VARCHAR(100) NOT NULL UNIQUE,
        projet_nom VARCHAR(255) NOT NULL,
        ville VARCHAR(150) NOT NULL DEFAULT 'Pointe Noire',
        pays VARCHAR(150) NOT NULL DEFAULT 'Congo',
        devise VARCHAR(20) NOT NULL DEFAULT 'FCFA',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS dim_lot (
        lot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        lot VARCHAR(255) NOT NULL UNIQUE,
        ordre_lot INTEGER NOT NULL DEFAULT 999,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS dim_niveau (
        niveau_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        niveau VARCHAR(100) NOT NULL UNIQUE,
        ordre_niveau INTEGER NOT NULL DEFAULT 999,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS dim_batiment (
        batiment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        batiment VARCHAR(150) NOT NULL UNIQUE,
        type_batiment VARCHAR(100) NOT NULL DEFAULT 'A_CLASSER',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS dim_supplier (
        supplier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        supplier_name VARCHAR(255) NOT NULL UNIQUE,
        country VARCHAR(150),
        risk_score DOUBLE PRECISION NOT NULL DEFAULT 0,
        quality_score DOUBLE PRECISION NOT NULL DEFAULT 0,
        lead_time_avg DOUBLE PRECISION NOT NULL DEFAULT 0,
        delivery_score DOUBLE PRECISION NOT NULL DEFAULT 0,
        financial_score DOUBLE PRECISION NOT NULL DEFAULT 0,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS dim_country (
        country_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        country_name VARCHAR(150) NOT NULL UNIQUE,
        customs_risk DOUBLE PRECISION NOT NULL DEFAULT 0,
        logistics_risk DOUBLE PRECISION NOT NULL DEFAULT 0,
        geopolitical_risk DOUBLE PRECISION NOT NULL DEFAULT 0,
        currency_risk DOUBLE PRECISION NOT NULL DEFAULT 0
    );

    CREATE SEQUENCE IF NOT EXISTS dim_famille_famille_id_seq;

    ALTER TABLE dim_famille
        ADD COLUMN IF NOT EXISTS famille_id BIGINT,
        ADD COLUMN IF NOT EXISTS categorie VARCHAR(100),
        ADD COLUMN IF NOT EXISTS importable BOOLEAN NOT NULL DEFAULT FALSE;

    UPDATE dim_famille
    SET famille_id = nextval('dim_famille_famille_id_seq')
    WHERE famille_id IS NULL;

    ALTER TABLE dim_famille
        ALTER COLUMN famille_id SET DEFAULT nextval('dim_famille_famille_id_seq');

    CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_famille_famille_id
        ON dim_famille (famille_id);

    INSERT INTO dim_projet (projet_code, projet_nom, ville, pays, devise)
    VALUES ('SP2I_DEFAULT', 'Centre medical Pointe Noire', 'Pointe Noire', 'Congo', 'FCFA')
    ON CONFLICT (projet_code) DO UPDATE SET updated_at = now();

    INSERT INTO dim_supplier (supplier_name, country)
    VALUES ('NON_RENSEIGNE', 'NON_RENSEIGNE')
    ON CONFLICT (supplier_name) DO NOTHING;

    INSERT INTO dim_country (country_name)
    VALUES ('NON_RENSEIGNE')
    ON CONFLICT (country_name) DO NOTHING;

    ALTER TABLE fact_metre
        ADD COLUMN IF NOT EXISTS projet_id BIGINT,
        ADD COLUMN IF NOT EXISTS lot_id BIGINT,
        ADD COLUMN IF NOT EXISTS niveau_id BIGINT,
        ADD COLUMN IF NOT EXISTS batiment_id BIGINT,
        ADD COLUMN IF NOT EXISTS famille_id BIGINT,
        ADD COLUMN IF NOT EXISTS scenario_id BIGINT,
        ADD COLUMN IF NOT EXISTS pu_local DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS pu_import DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS capex_local DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS capex_import DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS economie DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS taux_economie DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS date_import TIMESTAMPTZ NOT NULL DEFAULT now();

    INSERT INTO dim_lot (lot, ordre_lot)
    SELECT DISTINCT
        COALESCE(NULLIF(trim(lot), ''), 'NON_RENSEIGNE'),
        COALESCE(NULLIF(regexp_replace(COALESCE(lot, ''), '\\D', '', 'g'), '')::INTEGER, 999)
    FROM fact_metre
    ON CONFLICT (lot) DO NOTHING;

    INSERT INTO dim_niveau (niveau, ordre_niveau)
    SELECT DISTINCT COALESCE(NULLIF(trim(niveau), ''), 'GLOBAL'), 999
    FROM fact_metre
    ON CONFLICT (niveau) DO NOTHING;

    INSERT INTO dim_batiment (batiment, type_batiment)
    SELECT DISTINCT COALESCE(NULLIF(trim(batiment), ''), 'NON_RENSEIGNE'), 'A_CLASSER'
    FROM fact_metre
    ON CONFLICT (batiment) DO NOTHING;

    INSERT INTO dim_famille (famille, libelle_famille, categorie_achat, categorie, importable)
    SELECT DISTINCT
        COALESCE(NULLIF(trim(famille), ''), 'default'),
        COALESCE(NULLIF(trim(famille), ''), 'default'),
        'A_ANALYSER',
        'A_ANALYSER',
        false
    FROM fact_metre
    ON CONFLICT (famille) DO NOTHING;

    UPDATE fact_metre f
    SET
        projet_id = COALESCE(f.projet_id, p.projet_id),
        lot_id = COALESCE(f.lot_id, l.lot_id),
        niveau_id = COALESCE(f.niveau_id, n.niveau_id),
        batiment_id = COALESCE(f.batiment_id, b.batiment_id),
        famille_id = COALESCE(f.famille_id, df.famille_id),
        pu_local = COALESCE(f.pu_local, CASE WHEN COALESCE(f.quantite, 0) <> 0 THEN f.prix_total_ht / f.quantite ELSE 0 END),
        pu_import = COALESCE(f.pu_import, 0),
        capex_local = COALESCE(f.capex_local, f.prix_total_ht, 0),
        capex_import = COALESCE(f.capex_import, CASE WHEN f.decision_import = 'IMPORT' THEN f.capex_optimise ELSE 0 END, 0),
        economie = COALESCE(f.economie, f.economie_nette, 0),
        taux_economie = COALESCE(
            f.taux_economie,
            CASE WHEN COALESCE(f.prix_total_ht, 0) <> 0 THEN COALESCE(f.economie_nette, 0) / f.prix_total_ht ELSE 0 END
        ),
        scenario_id = COALESCE(f.scenario_id, 1)
    FROM dim_projet p, dim_lot l, dim_niveau n, dim_batiment b, dim_famille df
    WHERE p.projet_code = 'SP2I_DEFAULT'
      AND l.lot = COALESCE(NULLIF(trim(f.lot), ''), 'NON_RENSEIGNE')
      AND n.niveau = COALESCE(NULLIF(trim(f.niveau), ''), 'GLOBAL')
      AND b.batiment = COALESCE(NULLIF(trim(f.batiment), ''), 'NON_RENSEIGNE')
      AND df.famille = COALESCE(NULLIF(trim(f.famille), ''), 'default');

    CREATE INDEX IF NOT EXISTS ix_fact_metre_projet_id ON fact_metre (projet_id);
    CREATE INDEX IF NOT EXISTS ix_fact_metre_lot_id ON fact_metre (lot_id);
    CREATE INDEX IF NOT EXISTS ix_fact_metre_niveau_id ON fact_metre (niveau_id);
    CREATE INDEX IF NOT EXISTS ix_fact_metre_batiment_id ON fact_metre (batiment_id);
    CREATE INDEX IF NOT EXISTS ix_fact_metre_famille_id ON fact_metre (famille_id);
    """

    with engine.begin() as connection:
        connection.exec_driver_sql(sql)

    logger.info("Schema Power BI PostgreSQL verifie ou complete.")
