from __future__ import annotations

import logging

from sqlalchemy.engine import Engine

from app.analytics.sql import ANALYTICS_VIEWS_SQL


logger = logging.getLogger("sp2i-capex-api")


def ensure_powerbi_schema(engine: Engine) -> None:
    """
    Complete progressivement le schema PostgreSQL attendu par Power BI.

    `Base.metadata.create_all()` cree les tables manquantes, mais SQLAlchemy ne
    modifie pas automatiquement les tables deja existantes. Sur Render, une base
    peut donc contenir une ancienne version de `fact_metre` sans les colonnes
    analytiques (`capex_local`, `economie`, `lot_id`, etc.).

    Cette migration est volontairement idempotente :
    - elle ne supprime aucune table ;
    - elle n'efface aucune donnee ;
    - elle ajoute seulement les colonnes/dimensions manquantes ;
    - elle backfill les KPI a partir des colonnes historiques.
    """
    sql = """
    ALTER TABLE projects
        ADD COLUMN IF NOT EXISTS project_type VARCHAR(120) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS project_manager VARCHAR(255) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS target_budget DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS vat_mode VARCHAR(20) NOT NULL DEFAULT 'HT',
        ADD COLUMN IF NOT EXISTS reference_exchange_rate DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS default_transport_rate DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS default_customs_rate DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS default_insurance_rate DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS default_import_margin DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS minimum_saving_threshold DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS planned_start_date TIMESTAMPTZ,
        ADD COLUMN IF NOT EXISTS target_delivery_date TIMESTAMPTZ,
        ADD COLUMN IF NOT EXISTS site_storage_capacity DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS setup_status VARCHAR(40) NOT NULL DEFAULT 'CONFIG_REQUIRED',
        ADD COLUMN IF NOT EXISTS setup_completed_at TIMESTAMPTZ;

    UPDATE projects
    SET setup_status = CASE
        WHEN COALESCE(NULLIF(trim(name), ''), '') <> ''
         AND COALESCE(NULLIF(trim(client_name), ''), '') <> ''
         AND COALESCE(NULLIF(trim(city), ''), '') <> ''
         AND COALESCE(NULLIF(trim(country), ''), '') <> ''
         AND COALESCE(NULLIF(trim(currency), ''), '') <> ''
         AND COALESCE(NULLIF(trim(project_manager), ''), '') <> ''
        THEN 'CONFIGURED'
        ELSE 'CONFIG_REQUIRED'
    END;

    UPDATE projects
    SET setup_completed_at = COALESCE(setup_completed_at, now())
    WHERE setup_status = 'CONFIGURED';

    CREATE TABLE IF NOT EXISTS dim_projet (
        projet_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        projet_code VARCHAR(100) NOT NULL UNIQUE,
        projet_nom VARCHAR(255) NOT NULL,
        ville VARCHAR(150) NOT NULL DEFAULT 'Pointe Noire',
        pays VARCHAR(150) NOT NULL DEFAULT 'Congo',
        devise VARCHAR(20) NOT NULL DEFAULT 'FCFA',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS dim_lot (
        lot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        lot VARCHAR(255) NOT NULL UNIQUE,
        ordre_lot INTEGER NOT NULL DEFAULT 999,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS dim_sous_lot (
        sous_lot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        lot VARCHAR(255) NOT NULL DEFAULT '',
        sous_lot_code VARCHAR(80) NOT NULL DEFAULT '',
        sous_lot VARCHAR(255) NOT NULL,
        ordre_sous_lot INTEGER NOT NULL DEFAULT 999,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT ux_dim_sous_lot UNIQUE (lot, sous_lot_code, sous_lot)
    );

    CREATE TABLE IF NOT EXISTS dim_article_bpu (
        article_bpu_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        code_article VARCHAR(150) NOT NULL UNIQUE,
        lot VARCHAR(255) NOT NULL DEFAULT '',
        sous_lot VARCHAR(255) NOT NULL DEFAULT '',
        designation VARCHAR(500) NOT NULL DEFAULT '',
        unite VARCHAR(50) NOT NULL DEFAULT '',
        is_bim_compatible BOOLEAN NOT NULL DEFAULT FALSE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS dim_niveau (
        niveau_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        niveau VARCHAR(100) NOT NULL UNIQUE,
        ordre_niveau INTEGER NOT NULL DEFAULT 999,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS dim_batiment (
        batiment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        batiment VARCHAR(150) NOT NULL UNIQUE,
        type_batiment VARCHAR(100) NOT NULL DEFAULT 'A_CLASSER',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS dim_zone (
        zone_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        zone_code VARCHAR(180) NOT NULL UNIQUE,
        batiment VARCHAR(150) NOT NULL DEFAULT '',
        niveau VARCHAR(100) NOT NULL DEFAULT '',
        appart VARCHAR(150) NOT NULL DEFAULT '',
        piece VARCHAR(150) NOT NULL DEFAULT '',
        type_zone VARCHAR(100) NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    ALTER TABLE dim_batiment
        ADD COLUMN IF NOT EXISTS batiment_code VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS nom VARCHAR(255) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS nb_niveaux INTEGER NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS nb_appartements INTEGER NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS surface_totale_m2 DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS description VARCHAR(255) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE,
        ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

    ALTER TABLE dim_zone
        ADD COLUMN IF NOT EXISTS zone_nom VARCHAR(180) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS description VARCHAR(255) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE,
        ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

    CREATE TABLE IF NOT EXISTS dim_appart (
        appart_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        appart_code VARCHAR(180) NOT NULL UNIQUE,
        batiment VARCHAR(150) NOT NULL DEFAULT '',
        niveau VARCHAR(100) NOT NULL DEFAULT '',
        appart VARCHAR(150) NOT NULL DEFAULT '',
        type_appart VARCHAR(100) NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS dim_piece (
        piece_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        piece_code VARCHAR(180) NOT NULL UNIQUE,
        batiment VARCHAR(150) NOT NULL DEFAULT '',
        niveau VARCHAR(100) NOT NULL DEFAULT '',
        appart VARCHAR(150) NOT NULL DEFAULT '',
        piece VARCHAR(150) NOT NULL DEFAULT '',
        type_piece VARCHAR(100) NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS dim_appartement (
        appartement_id VARCHAR(150) PRIMARY KEY,
        niveau_id VARCHAR(150) NOT NULL DEFAULT '',
        description VARCHAR(255) NOT NULL DEFAULT '',
        type VARCHAR(100) NOT NULL DEFAULT '',
        surface DOUBLE PRECISION,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    ALTER TABLE dim_appartement
        ADD COLUMN IF NOT EXISTS appartement_code VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS batiment VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS niveau VARCHAR(100) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS surface_m2 DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS type_appartement VARCHAR(100) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS nb_chambres INTEGER NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS nb_sdb INTEGER NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE,
        ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

    ALTER TABLE dim_piece
        ADD COLUMN IF NOT EXISTS appartement_id VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS piece_nom VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS piece_type VARCHAR(100) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS surface_m2 DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS volume_m3 DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS zone VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS description VARCHAR(255) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE,
        ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

    CREATE TABLE IF NOT EXISTS dim_sous_lot_complet (
        sous_lot_id VARCHAR(150) PRIMARY KEY,
        lot_id VARCHAR(150) NOT NULL DEFAULT '',
        description VARCHAR(255) NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS dim_article_bpu_extended (
        article_id VARCHAR(150) PRIMARY KEY,
        lot_id VARCHAR(150) NOT NULL DEFAULT '',
        sous_lot_id VARCHAR(150) NOT NULL DEFAULT '',
        code_article VARCHAR(150) NOT NULL DEFAULT '',
        designation VARCHAR(500) NOT NULL DEFAULT '',
        marque VARCHAR(255) NOT NULL DEFAULT '',
        unite VARCHAR(50) NOT NULL DEFAULT '',
        ifc_class VARCHAR(150) NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS dim_article_bpu (
        code_article VARCHAR(150) PRIMARY KEY,
        designation VARCHAR(500) NOT NULL DEFAULT '',
        marque VARCHAR(255) NOT NULL DEFAULT '',
        unite VARCHAR(50) NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS dim_objet_bim (
        objet_bim_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        bim_object_id VARCHAR(150),
        ifc_guid VARCHAR(150),
        type_objet VARCHAR(150) NOT NULL DEFAULT '',
        famille_bim VARCHAR(255) NOT NULL DEFAULT '',
        systeme VARCHAR(150) NOT NULL DEFAULT '',
        phase_chantier VARCHAR(150) NOT NULL DEFAULT '',
        classification VARCHAR(150) NOT NULL DEFAULT '',
        omniclass VARCHAR(150) NOT NULL DEFAULT '',
        uniclass VARCHAR(150) NOT NULL DEFAULT '',
        ifc_type VARCHAR(150) NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS dim_supplier (
        supplier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        supplier_name VARCHAR(255) NOT NULL UNIQUE,
        country VARCHAR(150),
        risk_score DOUBLE PRECISION NOT NULL DEFAULT 0,
        quality_score DOUBLE PRECISION NOT NULL DEFAULT 0,
        lead_time_avg DOUBLE PRECISION NOT NULL DEFAULT 0,
        delivery_score DOUBLE PRECISION NOT NULL DEFAULT 0,
        financial_score DOUBLE PRECISION NOT NULL DEFAULT 0,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS dim_country (
        country_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        country_name VARCHAR(150) NOT NULL UNIQUE,
        customs_risk DOUBLE PRECISION NOT NULL DEFAULT 0,
        logistics_risk DOUBLE PRECISION NOT NULL DEFAULT 0,
        geopolitical_risk DOUBLE PRECISION NOT NULL DEFAULT 0,
        currency_risk DOUBLE PRECISION NOT NULL DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS dim_devise (
        devise_code VARCHAR(10) PRIMARY KEY,
        devise_nom VARCHAR(80) NOT NULL,
        symbole VARCHAR(10) NOT NULL,
        is_base BOOLEAN NOT NULL DEFAULT FALSE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS fact_change_rate (
        rate_id BIGSERIAL PRIMARY KEY,
        devise_source VARCHAR(10) NOT NULL REFERENCES dim_devise(devise_code),
        devise_cible VARCHAR(10) NOT NULL REFERENCES dim_devise(devise_code),
        taux DOUBLE PRECISION NOT NULL,
        source VARCHAR(100) NOT NULL DEFAULT 'SP2I_REFERENCE',
        date_taux DATE NOT NULL DEFAULT CURRENT_DATE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE SEQUENCE IF NOT EXISTS dim_famille_famille_id_seq;

    ALTER TABLE dim_famille
        ADD COLUMN IF NOT EXISTS famille_id BIGINT,
        ADD COLUMN IF NOT EXISTS categorie VARCHAR(100),
        ADD COLUMN IF NOT EXISTS importable BOOLEAN NOT NULL DEFAULT FALSE;

    UPDATE dim_famille
    SET famille_id = nextval('dim_famille_famille_id_seq')
    WHERE famille_id IS NULL;

    ALTER TABLE dim_famille
        ALTER COLUMN famille_id SET DEFAULT nextval('dim_famille_famille_id_seq');

    CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_famille_famille_id
        ON dim_famille (famille_id);

    INSERT INTO dim_projet (projet_code, projet_nom, ville, pays, devise)
    VALUES ('PROJET_MPEMBA', 'Complexe immobilier Mpemba', 'Pointe Noire', 'Congo', 'FCFA')
    ON CONFLICT (projet_code) DO UPDATE SET updated_at = now();

    INSERT INTO dim_supplier (supplier_name, country)
    VALUES ('NON_RENSEIGNE', 'NON_RENSEIGNE')
    ON CONFLICT (supplier_name) DO NOTHING;

    INSERT INTO dim_country (country_name)
    VALUES ('NON_RENSEIGNE')
    ON CONFLICT (country_name) DO NOTHING;

    INSERT INTO dim_batiment (
        batiment,
        batiment_code,
        nom,
        nb_niveaux,
        nb_appartements,
        surface_totale_m2,
        type_batiment,
        description,
        is_active
    )
    VALUES (
        'BATIMENT_01',
        'BATIMENT_01',
        'Batiment 01',
        3,
        6,
        1263.90,
        'RESIDENTIEL',
        'Batiment residentiel initial SP2I',
        true
    )
    ON CONFLICT (batiment) DO UPDATE SET
        batiment_code = EXCLUDED.batiment_code,
        nom = EXCLUDED.nom,
        nb_niveaux = EXCLUDED.nb_niveaux,
        nb_appartements = EXCLUDED.nb_appartements,
        surface_totale_m2 = EXCLUDED.surface_totale_m2,
        type_batiment = EXCLUDED.type_batiment,
        description = EXCLUDED.description,
        is_active = EXCLUDED.is_active,
        updated_at = now();

    INSERT INTO dim_zone (zone_code, zone_nom, type_zone, description, is_active)
    VALUES
        ('ZONE_JOUR', 'Jour', 'JOUR', 'Sejour, salon, cuisine et espaces de jour', true),
        ('ZONE_NUIT', 'Nuit', 'NUIT', 'Chambres et dressing', true),
        ('ZONE_SANITAIRE', 'Sanitaire', 'SANITAIRE', 'Salles d eau, salles de bain et WC', true),
        ('ZONE_CIRCULATION', 'Circulation', 'CIRCULATION', 'Couloirs et escaliers', true),
        ('ZONE_EXTERIEURE', 'Exterieure', 'EXTERIEUR', 'Balcons, terrasses et espaces exterieurs', true),
        ('ZONE_TECHNIQUE', 'Technique', 'TECHNIQUE', 'Locaux techniques et espaces non classes', true)
    ON CONFLICT (zone_code) DO UPDATE SET
        zone_nom = EXCLUDED.zone_nom,
        type_zone = EXCLUDED.type_zone,
        description = EXCLUDED.description,
        is_active = EXCLUDED.is_active,
        updated_at = now();

    INSERT INTO dim_devise (devise_code, devise_nom, symbole, is_base)
    VALUES
        ('FCFA', 'Franc CFA', 'FCFA', true),
        ('USD', 'Dollar americain', '$', false),
        ('EUR', 'Euro', 'EUR', false)
    ON CONFLICT (devise_code) DO NOTHING;

    INSERT INTO fact_change_rate (devise_source, devise_cible, taux, source)
    VALUES
        ('FCFA', 'FCFA', 1, 'SP2I_REFERENCE'),
        ('USD', 'FCFA', 610, 'SP2I_REFERENCE'),
        ('EUR', 'FCFA', 655.957, 'SP2I_REFERENCE')
    ON CONFLICT DO NOTHING;

    ALTER TABLE fact_metre
        ADD COLUMN IF NOT EXISTS projet_id BIGINT,
        ADD COLUMN IF NOT EXISTS project_code VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS lot_id BIGINT,
        ADD COLUMN IF NOT EXISTS lot_code VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS sous_lot_id VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS article_id VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS code_article VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS marque VARCHAR(255) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS unite VARCHAR(50) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS niveau_id BIGINT,
        ADD COLUMN IF NOT EXISTS niveau_code VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS batiment_id BIGINT,
        ADD COLUMN IF NOT EXISTS batiment_code VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS zone_id BIGINT,
        ADD COLUMN IF NOT EXISTS appart_id BIGINT,
        ADD COLUMN IF NOT EXISTS appartement_id VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS appartement_code VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS piece_id BIGINT,
        ADD COLUMN IF NOT EXISTS piece_code VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS objet_bim_id BIGINT,
        ADD COLUMN IF NOT EXISTS famille_id BIGINT,
        ADD COLUMN IF NOT EXISTS sous_lot VARCHAR(255) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS appart VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS piece VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS piece_type VARCHAR(100) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS type_zone VARCHAR(100) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS formule TEXT NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS bim_object_id VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS bim_object VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS ifc_guid VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS type_objet VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS famille_bim VARCHAR(255) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS systeme VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS phase_chantier VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS altitude DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS execution_status VARCHAR(50) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS workflow_status VARCHAR(50) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS eta TIMESTAMPTZ,
        ADD COLUMN IF NOT EXISTS risque VARCHAR(100) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS fournisseur VARCHAR(255) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS import_local VARCHAR(50) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS montant_import DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS decision VARCHAR(50) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS bim_maturity VARCHAR(50) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS source_file_type VARCHAR(100) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS classification VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS omniclass VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS uniclass VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS ifc_type VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS scenario_id BIGINT,
        ADD COLUMN IF NOT EXISTS pu_local DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS pu_import DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS capex_local DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS capex_import DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS economie DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS taux_economie DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS date_import TIMESTAMPTZ NOT NULL DEFAULT now(),
        ADD COLUMN IF NOT EXISTS devise_source VARCHAR(10) NOT NULL DEFAULT 'FCFA',
        ADD COLUMN IF NOT EXISTS montant_source DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS montant_fcfa DOUBLE PRECISION;

    INSERT INTO dim_appartement (appartement_id, niveau_id, description, type)
    VALUES ('COMMUN', 'GLOBAL', 'Parties communes', 'COMMUN')
    ON CONFLICT (appartement_id) DO UPDATE SET
        description = EXCLUDED.description,
        type = EXCLUDED.type,
        updated_at = now();

    INSERT INTO dim_appart (appart_code, appart, type_appart)
    VALUES ('COMMUN', 'COMMUN', 'COMMUN')
    ON CONFLICT (appart_code) DO UPDATE SET updated_at = now();

    INSERT INTO dim_piece (piece_code, piece, type_piece)
    VALUES ('TOITURE', 'TOITURE', 'Technique')
    ON CONFLICT (piece_code) DO UPDATE SET updated_at = now();

    UPDATE dim_appartement
    SET appartement_code = COALESCE(NULLIF(appartement_code, ''), appartement_id),
        type_appartement = COALESCE(NULLIF(type_appartement, ''), NULLIF(type, ''), ''),
        surface_m2 = COALESCE(surface_m2, surface),
        updated_at = now();

    UPDATE dim_piece
    SET piece_nom = COALESCE(NULLIF(piece_nom, ''), NULLIF(piece, ''), piece_code),
        piece_type = COALESCE(NULLIF(piece_type, ''), NULLIF(type_piece, ''), ''),
        updated_at = now();

    INSERT INTO dim_sous_lot_complet (sous_lot_id, lot_id, description)
    VALUES
        ('CAR_SOL', 'REVETEMENTS', 'Carrelage sols'),
        ('CVC_UI', 'CLIMATISATION', 'Unites interieures'),
        ('ELEC_EN', 'ELECTRICITE', 'Eclairage normal'),
        ('ELEC_PC', 'ELECTRICITE', 'Prises et commandes'),
        ('FP_BA13', 'FAUX_PLAFONDS', 'Faux plafonds BA13'),
        ('PNT_MUR', 'PEINTURE', 'Peinture murs'),
        ('SOL_PV', 'ENERGIE_SOLAIRE', 'Panneaux photovoltaiques'),
        ('TOIT_BAC', 'COUVERTURE', 'Bac acier')
    ON CONFLICT (sous_lot_id) DO UPDATE SET
        lot_id = EXCLUDED.lot_id,
        description = EXCLUDED.description,
        updated_at = now();

    INSERT INTO dim_lot (lot, ordre_lot)
    SELECT DISTINCT
        COALESCE(NULLIF(trim(lot), ''), 'NON_RENSEIGNE'),
        COALESCE(NULLIF(regexp_replace(COALESCE(lot, ''), '\\D', '', 'g'), '')::INTEGER, 999)
    FROM fact_metre
    ON CONFLICT (lot) DO NOTHING;

    INSERT INTO dim_lot (lot, ordre_lot)
    VALUES
        ('GROS_OEUVRE', 10),
        ('MACONNERIE', 20),
        ('ETANCHEITE', 30),
        ('CHARPENTE', 40),
        ('COUVERTURE', 50),
        ('MENUISERIE_ALU', 60),
        ('MENUISERIE_BOIS', 70),
        ('ELECTRICITE', 80),
        ('PLOMBERIE', 90),
        ('CLIMATISATION', 100),
        ('REVETEMENTS', 110),
        ('PEINTURE', 120),
        ('FAUX_PLAFONDS', 130),
        ('ASCENSEUR', 140),
        ('SMART_BUILDING', 150),
        ('SECURITE_INCENDIE', 160),
        ('VRD', 170),
        ('FACADE', 180),
        ('ENERGIE_SOLAIRE', 190)
    ON CONFLICT (lot) DO NOTHING;

    INSERT INTO dim_sous_lot (lot, sous_lot_code, sous_lot, ordre_sous_lot)
    VALUES
        ('ELECTRICITE', '11.1', 'APPAREILS_ECLAIRAGE_NORMAL', 111),
        ('ELECTRICITE', '11.2', 'ECLAIRAGE_BALISAGE', 112),
        ('ELECTRICITE', '11.3', 'PRISES_COMMANDES', 113),
        ('ELECTRICITE', '11.4', 'CABLES_FOURREAUX', 114),
        ('ELECTRICITE', '11.5', 'TABLEAUX', 115),
        ('ELECTRICITE', '11.6', 'TERRE', 116),
        ('ELECTRICITE', '11.7', 'SECOURS', 117),
        ('ELECTRICITE', '11.8', 'SOLAIRE', 118),
        ('ELECTRICITE', '11.9', 'CHEMINS_CABLES', 119),
        ('ELECTRICITE', '11.10', 'SMART_BUILDING', 120),
        ('PLOMBERIE', '12.1', 'ALIMENTATION_EAU', 121),
        ('PLOMBERIE', '12.2', 'EVACUATION', 122),
        ('PLOMBERIE', '12.3', 'APPAREILS_SANITAIRES', 123),
        ('CLIMATISATION', '13.1', 'GROUPES_EXTERIEURS', 131),
        ('CLIMATISATION', '13.2', 'RESEAUX_FRIGORIFIQUES', 132),
        ('CHARPENTE', '14.1', 'CHARPENTE_BOIS', 141),
        ('COUVERTURE', '14.2', 'BAC_ACIER', 142),
        ('FACADE', '15.1', 'MENUISERIE_FACADE', 151),
        ('VRD', '16.1', 'ACCES_CHANTIER', 161),
        ('SECURITE_INCENDIE', '17.1', 'DETECTION_INCENDIE', 171)
    ON CONFLICT (lot, sous_lot_code, sous_lot) DO NOTHING;

    INSERT INTO dim_niveau (niveau, ordre_niveau)
    SELECT DISTINCT COALESCE(NULLIF(trim(niveau), ''), 'GLOBAL'), 999
    FROM fact_metre
    ON CONFLICT (niveau) DO NOTHING;

    INSERT INTO dim_batiment (batiment, type_batiment)
    SELECT DISTINCT COALESCE(NULLIF(trim(batiment), ''), 'NON_RENSEIGNE'), 'A_CLASSER'
    FROM fact_metre
    ON CONFLICT (batiment) DO NOTHING;

    UPDATE dim_batiment
    SET batiment_code = COALESCE(NULLIF(batiment_code, ''), batiment),
        nom = COALESCE(NULLIF(nom, ''), batiment),
        updated_at = now();

    INSERT INTO dim_famille (famille, libelle_famille, categorie_achat, categorie, importable)
    SELECT DISTINCT
        COALESCE(NULLIF(trim(famille), ''), 'default'),
        COALESCE(NULLIF(trim(famille), ''), 'default'),
        'A_ANALYSER',
        'A_ANALYSER',
        false
    FROM fact_metre
    ON CONFLICT (famille) DO NOTHING;

    INSERT INTO dim_appartement (
        appartement_id,
        appartement_code,
        batiment,
        niveau,
        type_appartement,
        description
    )
    SELECT DISTINCT ON (COALESCE(NULLIF(trim(appartement_id), ''), NULLIF(trim(appartement_code), ''), NULLIF(trim(appart), ''), 'COMMUN'))
        COALESCE(NULLIF(trim(appartement_id), ''), NULLIF(trim(appartement_code), ''), NULLIF(trim(appart), ''), 'COMMUN') AS appartement_id,
        COALESCE(NULLIF(trim(appartement_code), ''), NULLIF(trim(appartement_id), ''), NULLIF(trim(appart), ''), 'COMMUN') AS appartement_code,
        COALESCE(NULLIF(trim(batiment), ''), 'NON_RENSEIGNE') AS batiment,
        COALESCE(NULLIF(trim(niveau), ''), 'GLOBAL') AS niveau,
        '',
        'Appartement detecte depuis FACT_METRE'
    FROM fact_metre
    WHERE COALESCE(NULLIF(trim(appartement_id), ''), NULLIF(trim(appartement_code), ''), NULLIF(trim(appart), '')) IS NOT NULL
    ORDER BY COALESCE(NULLIF(trim(appartement_id), ''), NULLIF(trim(appartement_code), ''), NULLIF(trim(appart), ''), 'COMMUN'), batiment, niveau
    ON CONFLICT (appartement_id) DO UPDATE SET
        appartement_code = COALESCE(NULLIF(dim_appartement.appartement_code, ''), EXCLUDED.appartement_code),
        batiment = COALESCE(NULLIF(dim_appartement.batiment, ''), EXCLUDED.batiment),
        niveau = COALESCE(NULLIF(dim_appartement.niveau, ''), EXCLUDED.niveau),
        updated_at = now();

    INSERT INTO dim_piece (
        piece_code,
        appartement_id,
        piece,
        piece_nom,
        type_piece,
        piece_type,
        zone,
        description
    )
    SELECT DISTINCT ON (COALESCE(NULLIF(trim(piece_code), ''), concat_ws('_',
            COALESCE(NULLIF(trim(appartement_id), ''), NULLIF(trim(appartement_code), ''), NULLIF(trim(appart), ''), 'COMMUN'),
            COALESCE(NULLIF(trim(piece), ''), 'PIECE')
        )))
        COALESCE(NULLIF(trim(piece_code), ''), concat_ws('_',
            COALESCE(NULLIF(trim(appartement_id), ''), NULLIF(trim(appartement_code), ''), NULLIF(trim(appart), ''), 'COMMUN'),
            COALESCE(NULLIF(trim(piece), ''), 'PIECE')
        )) AS piece_code,
        COALESCE(NULLIF(trim(appartement_id), ''), NULLIF(trim(appartement_code), ''), NULLIF(trim(appart), ''), 'COMMUN') AS appartement_id,
        COALESCE(NULLIF(trim(piece), ''), 'NON_RENSEIGNE') AS piece,
        COALESCE(NULLIF(trim(piece), ''), 'NON_RENSEIGNE') AS piece_nom,
        CASE
            WHEN upper(coalesce(piece, '')) LIKE '%SEJOUR%' OR upper(coalesce(piece, '')) LIKE '%SALON%' OR upper(coalesce(piece, '')) LIKE '%CUISINE%' THEN 'JOUR'
            WHEN upper(coalesce(piece, '')) LIKE '%CHAMBRE%' OR upper(coalesce(piece, '')) LIKE '%DRESSING%' THEN 'NUIT'
            WHEN upper(coalesce(piece, '')) LIKE '%SDE%' OR upper(coalesce(piece, '')) LIKE '%SDB%' OR upper(coalesce(piece, '')) LIKE '%WC%' THEN 'SANITAIRE'
            WHEN upper(coalesce(piece, '')) LIKE '%COULOIR%' OR upper(coalesce(piece, '')) LIKE '%ESCALIER%' THEN 'CIRCULATION'
            WHEN upper(coalesce(piece, '')) LIKE '%BALCON%' OR upper(coalesce(piece, '')) LIKE '%TERRASSE%' THEN 'EXTERIEUR'
            ELSE 'AUTRE'
        END AS type_piece,
        CASE
            WHEN upper(coalesce(piece, '')) LIKE '%SEJOUR%' OR upper(coalesce(piece, '')) LIKE '%SALON%' OR upper(coalesce(piece, '')) LIKE '%CUISINE%' THEN 'JOUR'
            WHEN upper(coalesce(piece, '')) LIKE '%CHAMBRE%' OR upper(coalesce(piece, '')) LIKE '%DRESSING%' THEN 'NUIT'
            WHEN upper(coalesce(piece, '')) LIKE '%SDE%' OR upper(coalesce(piece, '')) LIKE '%SDB%' OR upper(coalesce(piece, '')) LIKE '%WC%' THEN 'SANITAIRE'
            WHEN upper(coalesce(piece, '')) LIKE '%COULOIR%' OR upper(coalesce(piece, '')) LIKE '%ESCALIER%' THEN 'CIRCULATION'
            WHEN upper(coalesce(piece, '')) LIKE '%BALCON%' OR upper(coalesce(piece, '')) LIKE '%TERRASSE%' THEN 'EXTERIEUR'
            ELSE 'AUTRE'
        END AS piece_type,
        COALESCE(NULLIF(trim(batiment), ''), 'NON_RENSEIGNE') || '/' || COALESCE(NULLIF(trim(niveau), ''), 'GLOBAL') AS zone,
        'Piece detectee depuis FACT_METRE'
    FROM fact_metre
    WHERE COALESCE(NULLIF(trim(piece), ''), NULLIF(trim(piece_code), '')) IS NOT NULL
    ORDER BY COALESCE(NULLIF(trim(piece_code), ''), concat_ws('_',
            COALESCE(NULLIF(trim(appartement_id), ''), NULLIF(trim(appartement_code), ''), NULLIF(trim(appart), ''), 'COMMUN'),
            COALESCE(NULLIF(trim(piece), ''), 'PIECE')
        )), batiment, niveau, piece
    ON CONFLICT (piece_code) DO UPDATE SET
        appartement_id = COALESCE(NULLIF(dim_piece.appartement_id, ''), EXCLUDED.appartement_id),
        piece_nom = COALESCE(NULLIF(dim_piece.piece_nom, ''), EXCLUDED.piece_nom),
        piece_type = COALESCE(NULLIF(dim_piece.piece_type, ''), EXCLUDED.piece_type),
        type_piece = COALESCE(NULLIF(dim_piece.type_piece, ''), EXCLUDED.type_piece),
        zone = COALESCE(NULLIF(dim_piece.zone, ''), EXCLUDED.zone),
        updated_at = now();

    UPDATE fact_metre f
    SET
        projet_id = COALESCE(f.projet_id, p.projet_id),
        lot_id = COALESCE(f.lot_id, l.lot_id),
        niveau_id = COALESCE(f.niveau_id, n.niveau_id),
        batiment_id = COALESCE(f.batiment_id, b.batiment_id),
        famille_id = COALESCE(f.famille_id, df.famille_id),
        pu_local = COALESCE(f.pu_local, CASE WHEN COALESCE(f.quantite, 0) <> 0 THEN f.prix_total_ht / f.quantite ELSE 0 END),
        pu_import = COALESCE(f.pu_import, 0),
        capex_local = COALESCE(f.capex_local, f.prix_total_ht, 0),
        capex_import = COALESCE(f.capex_import, CASE WHEN f.decision_import = 'IMPORT' THEN f.capex_optimise ELSE 0 END, 0),
        montant_source = COALESCE(f.montant_source, f.capex_local, f.prix_total_ht, 0),
        montant_fcfa = COALESCE(f.montant_fcfa, f.capex_local, f.prix_total_ht, 0),
        economie = COALESCE(f.economie, f.economie_nette, 0),
        taux_economie = COALESCE(
            f.taux_economie,
            CASE WHEN COALESCE(f.prix_total_ht, 0) <> 0 THEN COALESCE(f.economie_nette, 0) / f.prix_total_ht ELSE 0 END
        ),
        scenario_id = COALESCE(f.scenario_id, 1)
    FROM dim_projet p, dim_lot l, dim_niveau n, dim_batiment b, dim_famille df
    WHERE p.projet_code = 'PROJET_MPEMBA'
      AND l.lot = COALESCE(NULLIF(trim(f.lot), ''), 'NON_RENSEIGNE')
      AND n.niveau = COALESCE(NULLIF(trim(f.niveau), ''), 'GLOBAL')
      AND b.batiment = COALESCE(NULLIF(trim(f.batiment), ''), 'NON_RENSEIGNE')
      AND df.famille = COALESCE(NULLIF(trim(f.famille), ''), 'default');

    INSERT INTO dim_sous_lot_complet (sous_lot_id, lot_id, description)
    SELECT DISTINCT
        COALESCE(NULLIF(upper(trim(f.sous_lot_id)), ''), COALESCE(NULLIF(upper(trim(f.sous_lot)), ''), 'NON_RENSEIGNE')),
        COALESCE(NULLIF(upper(trim(f.lot)), ''), 'NON_RENSEIGNE'),
        COALESCE(NULLIF(trim(f.sous_lot), ''), COALESCE(NULLIF(trim(f.sous_lot_id), ''), 'Non renseigne'))
    FROM fact_metre f
    WHERE COALESCE(NULLIF(trim(f.sous_lot_id), ''), NULLIF(trim(f.sous_lot), '')) IS NOT NULL
    ON CONFLICT (sous_lot_id) DO UPDATE SET
        lot_id = EXCLUDED.lot_id,
        description = EXCLUDED.description,
        updated_at = now();

    INSERT INTO dim_article_bpu_extended (
        article_id, lot_id, sous_lot_id, code_article, designation, marque, unite, ifc_class
    )
    SELECT DISTINCT
        COALESCE(NULLIF(upper(trim(f.article_id)), ''), COALESCE(NULLIF(upper(trim(f.id_ligne)), ''), 'ARTICLE_NON_RENSEIGNE')),
        COALESCE(NULLIF(upper(trim(f.lot)), ''), 'NON_RENSEIGNE'),
        COALESCE(NULLIF(upper(trim(f.sous_lot_id)), ''), COALESCE(NULLIF(upper(trim(f.sous_lot)), ''), 'NON_RENSEIGNE')),
        COALESCE(NULLIF(upper(trim(f.code_article)), ''), COALESCE(NULLIF(upper(trim(f.id_ligne)), ''), '')),
        COALESCE(NULLIF(trim(f.designation), ''), 'Designation non renseignee'),
        COALESCE(NULLIF(trim(f.marque), ''), ''),
        COALESCE(NULLIF(trim(f.unite), ''), ''),
        COALESCE(NULLIF(trim(f.ifc_type), ''), NULLIF(trim(f.bim_object), ''), '')
    FROM fact_metre f
    WHERE COALESCE(NULLIF(trim(f.article_id), ''), NULLIF(trim(f.id_ligne), '')) IS NOT NULL
    ON CONFLICT (article_id) DO UPDATE SET
        lot_id = EXCLUDED.lot_id,
        sous_lot_id = EXCLUDED.sous_lot_id,
        code_article = EXCLUDED.code_article,
        designation = EXCLUDED.designation,
        marque = EXCLUDED.marque,
        unite = EXCLUDED.unite,
        ifc_class = EXCLUDED.ifc_class,
        updated_at = now();

    CREATE INDEX IF NOT EXISTS ix_fact_metre_projet_id ON fact_metre (projet_id);
    CREATE INDEX IF NOT EXISTS ix_fact_metre_lot_id ON fact_metre (lot_id);
    CREATE INDEX IF NOT EXISTS ix_fact_metre_niveau_id ON fact_metre (niveau_id);
    CREATE INDEX IF NOT EXISTS ix_fact_metre_batiment_id ON fact_metre (batiment_id);
    CREATE INDEX IF NOT EXISTS ix_fact_metre_zone_id ON fact_metre (zone_id);
    CREATE INDEX IF NOT EXISTS ix_fact_metre_appart_id ON fact_metre (appart_id);
    CREATE INDEX IF NOT EXISTS ix_fact_metre_piece_id ON fact_metre (piece_id);
    CREATE INDEX IF NOT EXISTS ix_fact_metre_objet_bim_id ON fact_metre (objet_bim_id);
    CREATE INDEX IF NOT EXISTS ix_fact_metre_spatial ON fact_metre (batiment, niveau, piece);
    CREATE INDEX IF NOT EXISTS ix_fact_metre_bim_scope ON fact_metre (batiment, niveau, appartement_id, piece, lot);
    CREATE INDEX IF NOT EXISTS ix_fact_metre_ifc_guid ON fact_metre (ifc_guid);
    CREATE INDEX IF NOT EXISTS ix_fact_metre_famille_id ON fact_metre (famille_id);
    CREATE INDEX IF NOT EXISTS ix_fact_metre_project_execution ON fact_metre (projet_id, execution_status);
    CREATE INDEX IF NOT EXISTS ix_fact_metre_project_workflow ON fact_metre (projet_id, workflow_status);
    CREATE INDEX IF NOT EXISTS ix_fact_metre_project_eta ON fact_metre (projet_id, eta);
    CREATE INDEX IF NOT EXISTS ix_fact_metre_article_id ON fact_metre (article_id);
    CREATE INDEX IF NOT EXISTS ix_fact_metre_sous_lot_id ON fact_metre (sous_lot_id);
    CREATE INDEX IF NOT EXISTS ix_dim_batiment_code ON dim_batiment (batiment_code);
    CREATE INDEX IF NOT EXISTS ix_dim_zone_code ON dim_zone (zone_code);
    CREATE INDEX IF NOT EXISTS ix_dim_zone_type ON dim_zone (type_zone);
    CREATE INDEX IF NOT EXISTS ix_dim_appartement_plan_scope
        ON dim_appartement (batiment, niveau, appartement_code);
    CREATE INDEX IF NOT EXISTS ix_dim_piece_plan_scope
        ON dim_piece (appartement_id, piece_nom, piece_type);
    CREATE INDEX IF NOT EXISTS ix_fact_metre_enterprise_upsert
        ON fact_metre (article_id, ifc_guid, niveau_code, appartement_id, piece_code);
    CREATE INDEX IF NOT EXISTS ix_dim_sous_lot_lot ON dim_sous_lot (lot);
    CREATE INDEX IF NOT EXISTS ix_dim_article_bpu_lot ON dim_article_bpu (lot);

    CREATE TABLE IF NOT EXISTS dim_scenario (
        scenario_id UUID PRIMARY KEY,
        projet_id BIGINT NULL REFERENCES dim_projet(projet_id),
        scenario_nom VARCHAR(255) NOT NULL,
        scenario_type VARCHAR(100) NOT NULL DEFAULT 'BASELINE',
        description TEXT NOT NULL DEFAULT '',
        parameters_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        is_baseline BOOLEAN NOT NULL DEFAULT FALSE,
        created_by VARCHAR(150) NOT NULL DEFAULT 'system',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS simulation_run (
        run_id UUID PRIMARY KEY,
        scenario_id UUID NOT NULL REFERENCES dim_scenario(scenario_id) ON DELETE CASCADE,
        projet_id BIGINT NULL REFERENCES dim_projet(projet_id),
        source_file VARCHAR(500) NOT NULL DEFAULT '',
        source_type VARCHAR(100) NOT NULL DEFAULT 'API',
        rows_in INTEGER NOT NULL DEFAULT 0,
        rows_out INTEGER NOT NULL DEFAULT 0,
        rows_rejected INTEGER NOT NULL DEFAULT 0,
        warnings_json JSONB NOT NULL DEFAULT '[]'::jsonb,
        errors_json JSONB NOT NULL DEFAULT '[]'::jsonb,
        duration_ms INTEGER NOT NULL DEFAULT 0,
        started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        ended_at TIMESTAMPTZ NULL,
        status VARCHAR(50) NOT NULL DEFAULT 'RUNNING'
    );

    CREATE TABLE IF NOT EXISTS fact_simulation (
        simulation_line_id BIGSERIAL PRIMARY KEY,
        simulation_id UUID NOT NULL,
        scenario_id UUID NOT NULL REFERENCES dim_scenario(scenario_id) ON DELETE CASCADE,
        run_id UUID NOT NULL REFERENCES simulation_run(run_id) ON DELETE CASCADE,
        projet_id BIGINT NULL REFERENCES dim_projet(projet_id),
        id_ligne VARCHAR(100) NOT NULL DEFAULT '',
        lot_id BIGINT NULL REFERENCES dim_lot(lot_id),
        famille_id BIGINT NULL REFERENCES dim_famille(famille_id),
        niveau_id BIGINT NULL REFERENCES dim_niveau(niveau_id),
        batiment_id BIGINT NULL REFERENCES dim_batiment(batiment_id),
        designation VARCHAR(500) NOT NULL DEFAULT '',
        quantite DOUBLE PRECISION NOT NULL DEFAULT 0,
        pu_local DOUBLE PRECISION NOT NULL DEFAULT 0,
        pu_import DOUBLE PRECISION NOT NULL DEFAULT 0,
        capex_local DOUBLE PRECISION NOT NULL DEFAULT 0,
        capex_import DOUBLE PRECISION NOT NULL DEFAULT 0,
        capex_optimise DOUBLE PRECISION NOT NULL DEFAULT 0,
        economie DOUBLE PRECISION NOT NULL DEFAULT 0,
        taux_economie DOUBLE PRECISION NOT NULL DEFAULT 0,
        decision_import VARCHAR(50) NOT NULL DEFAULT 'LOCAL',
        score_confiance DOUBLE PRECISION NOT NULL DEFAULT 0,
        statut_qualite VARCHAR(150) NOT NULL DEFAULT 'OK',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    ALTER TABLE fact_simulation
        ADD COLUMN IF NOT EXISTS decision_score DOUBLE PRECISION NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS risk_score DOUBLE PRECISION NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS lead_time_score DOUBLE PRECISION NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS criticality_score DOUBLE PRECISION NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS decision_reason JSONB NOT NULL DEFAULT '{}'::jsonb,
        ADD COLUMN IF NOT EXISTS decision_type VARCHAR(100) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS decision_confidence VARCHAR(50) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS global_risk_score DOUBLE PRECISION NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS lead_time_days DOUBLE PRECISION NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS cashflow_score DOUBLE PRECISION NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS moq_risk_score DOUBLE PRECISION NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS complexity_score DOUBLE PRECISION NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS procurement_reason JSONB NOT NULL DEFAULT '{}'::jsonb,
        ADD COLUMN IF NOT EXISTS container_strategy VARCHAR(100) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS shipment_strategy VARCHAR(100) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS fill_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS shipment_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS lead_time_total DOUBLE PRECISION NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS storage_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS delivery_risk VARCHAR(100) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS logistics_reason JSONB NOT NULL DEFAULT '{}'::jsonb,
        ADD COLUMN IF NOT EXISTS supplier_id BIGINT NULL REFERENCES dim_supplier(supplier_id),
        ADD COLUMN IF NOT EXISTS country_id BIGINT NULL REFERENCES dim_country(country_id);

    CREATE INDEX IF NOT EXISTS ix_dim_scenario_created_at ON dim_scenario(created_at);
    CREATE INDEX IF NOT EXISTS ix_fact_simulation_scenario_id ON fact_simulation(scenario_id);
    CREATE INDEX IF NOT EXISTS ix_simulation_run_scenario_id ON simulation_run(scenario_id);

    CREATE TABLE IF NOT EXISTS dqe_import_audit (
        import_id BIGSERIAL PRIMARY KEY,
        fichier VARCHAR(500) NOT NULL DEFAULT '',
        statut VARCHAR(50) NOT NULL DEFAULT 'SUCCESS',
        score_qualite DOUBLE PRECISION NOT NULL DEFAULT 0,
        lignes_excel INTEGER NOT NULL DEFAULT 0,
        lignes_parsees INTEGER NOT NULL DEFAULT 0,
        lignes_fact_metre INTEGER NOT NULL DEFAULT 0,
        lignes_rejetees INTEGER NOT NULL DEFAULT 0,
        lignes_review_required INTEGER NOT NULL DEFAULT 0,
        lignes_warning INTEGER NOT NULL DEFAULT 0,
        lignes_ignorees INTEGER NOT NULL DEFAULT 0,
        capex_source DOUBLE PRECISION NOT NULL DEFAULT 0,
        capex_fact_metre DOUBLE PRECISION NOT NULL DEFAULT 0,
        ecart_capex DOUBLE PRECISION NOT NULL DEFAULT 0,
        ecart_capex_pct DOUBLE PRECISION NOT NULL DEFAULT 0,
        lots_detectes INTEGER NOT NULL DEFAULT 0,
        colonnes_reconnues INTEGER NOT NULL DEFAULT 0,
        anomalies_json JSONB NOT NULL DEFAULT '[]'::jsonb,
        governance_quality JSONB NOT NULL DEFAULT '{}'::jsonb,
        metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        created_by VARCHAR(150) NOT NULL DEFAULT 'system',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    ALTER TABLE dqe_import_audit
        ADD COLUMN IF NOT EXISTS lignes_rejetees INTEGER NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS lignes_review_required INTEGER NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS lignes_warning INTEGER NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS lignes_ignorees INTEGER NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS governance_quality JSONB NOT NULL DEFAULT '{}'::jsonb;

    CREATE INDEX IF NOT EXISTS ix_dqe_import_audit_created_at ON dqe_import_audit(created_at);

    CREATE TABLE IF NOT EXISTS procurement_decisions (
        id BIGSERIAL PRIMARY KEY,
        project_id INTEGER NOT NULL,
        scenario_id VARCHAR(36) NULL,
        simulation_line_id BIGINT NULL,
        lot VARCHAR(255) NOT NULL DEFAULT '',
        family VARCHAR(255) NOT NULL DEFAULT '',
        designation VARCHAR(500) NOT NULL DEFAULT '',
        quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
        unit VARCHAR(50) NOT NULL DEFAULT '',
        ai_decision VARCHAR(50) NOT NULL DEFAULT 'REVIEW_REQUIRED',
        ai_score DOUBLE PRECISION NOT NULL DEFAULT 0,
        ai_reason TEXT NOT NULL DEFAULT '',
        proposed_decision VARCHAR(50) NOT NULL DEFAULT 'REVIEW_REQUIRED',
        validated_decision VARCHAR(50) NOT NULL DEFAULT '',
        validation_status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
        supplier_selected VARCHAR(255) NOT NULL DEFAULT '',
        supplier_country VARCHAR(150) NOT NULL DEFAULT '',
        purchase_mode VARCHAR(50) NOT NULL DEFAULT '',
        estimated_local_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
        estimated_import_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
        estimated_savings DOUBLE PRECISION NOT NULL DEFAULT 0,
        risk_level VARCHAR(50) NOT NULL DEFAULT 'MEDIUM',
        validator_name VARCHAR(255) NOT NULL DEFAULT '',
        validator_id INTEGER NULL,
        validated_at TIMESTAMPTZ NULL,
        comment TEXT NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    ALTER TABLE procurement_decisions
        ADD COLUMN IF NOT EXISTS project_id INTEGER NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS scenario_id VARCHAR(36) NULL,
        ADD COLUMN IF NOT EXISTS simulation_line_id BIGINT NULL,
        ADD COLUMN IF NOT EXISTS lot VARCHAR(255) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS family VARCHAR(255) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS designation VARCHAR(500) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS unit VARCHAR(50) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS ai_decision VARCHAR(50) NOT NULL DEFAULT 'REVIEW_REQUIRED',
        ADD COLUMN IF NOT EXISTS ai_score DOUBLE PRECISION NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS ai_reason TEXT NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS proposed_decision VARCHAR(50) NOT NULL DEFAULT 'REVIEW_REQUIRED',
        ADD COLUMN IF NOT EXISTS validated_decision VARCHAR(50) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS validation_status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
        ADD COLUMN IF NOT EXISTS supplier_selected VARCHAR(255) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS supplier_country VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS purchase_mode VARCHAR(50) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS estimated_local_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS estimated_import_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS estimated_savings DOUBLE PRECISION NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS risk_level VARCHAR(50) NOT NULL DEFAULT 'MEDIUM',
        ADD COLUMN IF NOT EXISTS validator_name VARCHAR(255) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS validator_id INTEGER NULL,
        ADD COLUMN IF NOT EXISTS validated_at TIMESTAMPTZ NULL,
        ADD COLUMN IF NOT EXISTS comment TEXT NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

    CREATE UNIQUE INDEX IF NOT EXISTS ux_procurement_decision_source_line
        ON procurement_decisions (project_id, scenario_id, simulation_line_id)
        ;

    CREATE INDEX IF NOT EXISTS ix_procurement_decisions_project_status
        ON procurement_decisions (project_id, validation_status);

    CREATE INDEX IF NOT EXISTS ix_procurement_decisions_scenario
        ON procurement_decisions (scenario_id);

    CREATE TABLE IF NOT EXISTS site_execution_actions (
        id BIGSERIAL PRIMARY KEY,
        project_id INTEGER NOT NULL,
        scenario_id VARCHAR(36) NULL,
        procurement_decision_id BIGINT NULL,
        simulation_line_id BIGINT NULL,
        batiment VARCHAR(150) NOT NULL DEFAULT '',
        niveau VARCHAR(100) NOT NULL DEFAULT '',
        appart VARCHAR(150) NOT NULL DEFAULT '',
        piece VARCHAR(150) NOT NULL DEFAULT '',
        type_zone VARCHAR(100) NOT NULL DEFAULT '',
        bim_object_id VARCHAR(150) NOT NULL DEFAULT '',
        ifc_guid VARCHAR(150) NOT NULL DEFAULT '',
        lot VARCHAR(255) NOT NULL DEFAULT '',
        family VARCHAR(255) NOT NULL DEFAULT '',
        designation VARCHAR(500) NOT NULL DEFAULT '',
        action_type VARCHAR(50) NOT NULL DEFAULT 'COORDINATION',
        title VARCHAR(255) NOT NULL DEFAULT '',
        problem TEXT NOT NULL DEFAULT '',
        impact TEXT NOT NULL DEFAULT '',
        recommended_action TEXT NOT NULL DEFAULT '',
        priority VARCHAR(50) NOT NULL DEFAULT 'MEDIUM',
        risk_level VARCHAR(50) NOT NULL DEFAULT 'MEDIUM',
        status VARCHAR(50) NOT NULL DEFAULT 'TO_DO',
        responsible_role VARCHAR(150) NOT NULL DEFAULT '',
        responsible_name VARCHAR(255) NOT NULL DEFAULT '',
        due_date TIMESTAMPTZ NULL,
        started_at TIMESTAMPTZ NULL,
        completed_at TIMESTAMPTZ NULL,
        delivery_eta_days DOUBLE PRECISION NOT NULL DEFAULT 0,
        date_needed TIMESTAMPTZ NULL,
        delay_days DOUBLE PRECISION NOT NULL DEFAULT 0,
        storage_impact DOUBLE PRECISION NOT NULL DEFAULT 0,
        criticality_score DOUBLE PRECISION NOT NULL DEFAULT 0,
        source VARCHAR(100) NOT NULL DEFAULT 'procurement_decisions',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    ALTER TABLE site_execution_actions
        ADD COLUMN IF NOT EXISTS project_id INTEGER NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS scenario_id VARCHAR(36) NULL,
        ADD COLUMN IF NOT EXISTS procurement_decision_id BIGINT NULL,
        ADD COLUMN IF NOT EXISTS simulation_line_id BIGINT NULL,
        ADD COLUMN IF NOT EXISTS batiment VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS niveau VARCHAR(100) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS appart VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS piece VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS type_zone VARCHAR(100) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS bim_object_id VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS ifc_guid VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS lot VARCHAR(255) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS family VARCHAR(255) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS designation VARCHAR(500) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS action_type VARCHAR(50) NOT NULL DEFAULT 'COORDINATION',
        ADD COLUMN IF NOT EXISTS title VARCHAR(255) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS problem TEXT NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS impact TEXT NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS recommended_action TEXT NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS priority VARCHAR(50) NOT NULL DEFAULT 'MEDIUM',
        ADD COLUMN IF NOT EXISTS risk_level VARCHAR(50) NOT NULL DEFAULT 'MEDIUM',
        ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'TO_DO',
        ADD COLUMN IF NOT EXISTS responsible_role VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS responsible_name VARCHAR(255) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS due_date TIMESTAMPTZ NULL,
        ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ NULL,
        ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ NULL,
        ADD COLUMN IF NOT EXISTS delivery_eta_days DOUBLE PRECISION NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS date_needed TIMESTAMPTZ NULL,
        ADD COLUMN IF NOT EXISTS delay_days DOUBLE PRECISION NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS storage_impact DOUBLE PRECISION NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS criticality_score DOUBLE PRECISION NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS source VARCHAR(100) NOT NULL DEFAULT 'procurement_decisions',
        ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

    CREATE UNIQUE INDEX IF NOT EXISTS ux_site_execution_action_source
        ON site_execution_actions (project_id, scenario_id, procurement_decision_id, action_type);

    CREATE INDEX IF NOT EXISTS ix_site_execution_actions_project_status
        ON site_execution_actions (project_id, status);

    CREATE INDEX IF NOT EXISTS ix_site_execution_actions_scenario
        ON site_execution_actions (scenario_id);

    CREATE INDEX IF NOT EXISTS ix_site_execution_actions_spatial
        ON site_execution_actions (project_id, batiment, niveau, piece);

    CREATE TABLE IF NOT EXISTS workflow_events (
        id BIGSERIAL PRIMARY KEY,
        project_id INTEGER NOT NULL,
        user_id INTEGER NULL,
        event_type VARCHAR(100) NOT NULL DEFAULT '',
        entity_type VARCHAR(100) NOT NULL DEFAULT '',
        entity_id VARCHAR(100) NOT NULL DEFAULT '',
        previous_status VARCHAR(100) NOT NULL DEFAULT '',
        new_status VARCHAR(100) NOT NULL DEFAULT '',
        message TEXT NOT NULL DEFAULT '',
        metadata_json TEXT NOT NULL DEFAULT '{}'::text,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    ALTER TABLE workflow_events
        ADD COLUMN IF NOT EXISTS project_id INTEGER NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS user_id INTEGER NULL,
        ADD COLUMN IF NOT EXISTS event_type VARCHAR(100) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS entity_type VARCHAR(100) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS entity_id VARCHAR(100) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS previous_status VARCHAR(100) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS new_status VARCHAR(100) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS message TEXT NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS metadata_json TEXT NOT NULL DEFAULT '{}'::text,
        ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

    CREATE INDEX IF NOT EXISTS ix_workflow_events_project_created
        ON workflow_events (project_id, created_at DESC);

    CREATE INDEX IF NOT EXISTS ix_workflow_events_project_type
        ON workflow_events (project_id, event_type);

    CREATE TABLE IF NOT EXISTS fact_approvals (
        approval_id BIGSERIAL PRIMARY KEY,
        project_id BIGINT NOT NULL,
        simulation_id VARCHAR(100) NOT NULL DEFAULT '',
        procurement_action_id BIGINT NULL,
        article_id VARCHAR(150) NOT NULL DEFAULT '',
        lot_id VARCHAR(150) NOT NULL DEFAULT '',
        sous_lot_id VARCHAR(150) NOT NULL DEFAULT '',
        niveau_id VARCHAR(150) NOT NULL DEFAULT '',
        appartement_id VARCHAR(150) NOT NULL DEFAULT '',
        piece_id VARCHAR(150) NOT NULL DEFAULT '',
        ifc_guid VARCHAR(150) NOT NULL DEFAULT '',
        approval_type VARCHAR(80) NOT NULL DEFAULT 'PROCUREMENT_ARBITRATION',
        decision VARCHAR(80) NOT NULL DEFAULT 'A_ARBITRER',
        status VARCHAR(80) NOT NULL DEFAULT 'PENDING',
        priority VARCHAR(40) NOT NULL DEFAULT 'MEDIUM',
        risk_level VARCHAR(40) NOT NULL DEFAULT 'MEDIUM',
        roi DOUBLE PRECISION NULL,
        estimated_saving DOUBLE PRECISION NULL,
        eta TIMESTAMPTZ NULL,
        justification_ai TEXT NOT NULL DEFAULT '',
        justification_human TEXT NOT NULL DEFAULT '',
        requested_by VARCHAR(255) NOT NULL DEFAULT '',
        assigned_to VARCHAR(255) NOT NULL DEFAULT '',
        approved_by VARCHAR(255) NOT NULL DEFAULT '',
        rejected_by VARCHAR(255) NOT NULL DEFAULT '',
        role_required VARCHAR(120) NOT NULL DEFAULT 'PROCUREMENT_MANAGER',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        approved_at TIMESTAMPTZ NULL,
        rejected_at TIMESTAMPTZ NULL,
        deadline TIMESTAMPTZ NULL
    );

    ALTER TABLE fact_approvals
        ADD COLUMN IF NOT EXISTS project_id BIGINT NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS simulation_id VARCHAR(100) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS procurement_action_id BIGINT NULL,
        ADD COLUMN IF NOT EXISTS article_id VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS lot_id VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS sous_lot_id VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS niveau_id VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS appartement_id VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS piece_id VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS ifc_guid VARCHAR(150) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS approval_type VARCHAR(80) NOT NULL DEFAULT 'PROCUREMENT_ARBITRATION',
        ADD COLUMN IF NOT EXISTS decision VARCHAR(80) NOT NULL DEFAULT 'A_ARBITRER',
        ADD COLUMN IF NOT EXISTS status VARCHAR(80) NOT NULL DEFAULT 'PENDING',
        ADD COLUMN IF NOT EXISTS priority VARCHAR(40) NOT NULL DEFAULT 'MEDIUM',
        ADD COLUMN IF NOT EXISTS risk_level VARCHAR(40) NOT NULL DEFAULT 'MEDIUM',
        ADD COLUMN IF NOT EXISTS roi DOUBLE PRECISION NULL,
        ADD COLUMN IF NOT EXISTS estimated_saving DOUBLE PRECISION NULL,
        ADD COLUMN IF NOT EXISTS eta TIMESTAMPTZ NULL,
        ADD COLUMN IF NOT EXISTS justification_ai TEXT NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS justification_human TEXT NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS requested_by VARCHAR(255) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS assigned_to VARCHAR(255) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS approved_by VARCHAR(255) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS rejected_by VARCHAR(255) NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS role_required VARCHAR(120) NOT NULL DEFAULT 'PROCUREMENT_MANAGER',
        ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ NULL,
        ADD COLUMN IF NOT EXISTS rejected_at TIMESTAMPTZ NULL,
        ADD COLUMN IF NOT EXISTS deadline TIMESTAMPTZ NULL;

    CREATE INDEX IF NOT EXISTS ix_fact_approvals_project_status
        ON fact_approvals (project_id, status);

    CREATE INDEX IF NOT EXISTS ix_fact_approvals_project_type
        ON fact_approvals (project_id, approval_type);

    CREATE INDEX IF NOT EXISTS ix_fact_approvals_project_deadline
        ON fact_approvals (project_id, deadline);

    CREATE INDEX IF NOT EXISTS ix_fact_approvals_governance_queue
        ON fact_approvals (project_id, role_required, status, priority);

    CREATE INDEX IF NOT EXISTS ix_fact_approvals_procurement_action
        ON fact_approvals (procurement_action_id);

    CREATE INDEX IF NOT EXISTS ix_fact_approvals_ifc_guid
        ON fact_approvals (ifc_guid);
    """

    with engine.begin() as connection:
        connection.exec_driver_sql(sql)
        connection.exec_driver_sql(ANALYTICS_VIEWS_SQL)

    logger.info("Schema Power BI PostgreSQL verifie ou complete.")
