/*
SP2I CAPEX - STAR SCHEMA PostgreSQL pour Power BI

Objectif :
- conserver fact_metre et dim_famille existantes ;
- ajouter progressivement les dimensions manquantes ;
- ajouter des cles techniques stables pour les relations Power BI ;
- creer des vues KPI pre-calculees cote PostgreSQL ;
- ne pas deplacer la logique metier dans Power BI.

Ce script est idempotent : il peut etre relance sans detruire les donnees.
*/

BEGIN;

/* -------------------------------------------------------------------------
1. EXTENSION PROGRESSIVE DES TABLES EXISTANTES
--------------------------------------------------------------------------- */

CREATE SEQUENCE IF NOT EXISTS dim_famille_famille_id_seq;

ALTER TABLE dim_famille
    ADD COLUMN IF NOT EXISTS famille_id BIGINT,
    ADD COLUMN IF NOT EXISTS categorie VARCHAR(100),
    ADD COLUMN IF NOT EXISTS importable BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE dim_famille
SET famille_id = nextval('dim_famille_famille_id_seq')
WHERE famille_id IS NULL;

UPDATE dim_famille
SET
    categorie = COALESCE(NULLIF(categorie, ''), categorie_achat),
    importable = COALESCE(NULLIF(categorie, ''), categorie_achat) = 'IMPORTABLE'
WHERE categorie IS NULL OR categorie = '' OR importable IS NULL;

ALTER TABLE dim_famille
    ALTER COLUMN famille_id SET NOT NULL;

ALTER SEQUENCE dim_famille_famille_id_seq
    OWNED BY dim_famille.famille_id;

ALTER TABLE dim_famille
    ALTER COLUMN famille_id SET DEFAULT nextval('dim_famille_famille_id_seq');

CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_famille_famille_id
    ON dim_famille (famille_id);

/* -------------------------------------------------------------------------
2. DIMENSIONS DU STAR SCHEMA
--------------------------------------------------------------------------- */

CREATE TABLE IF NOT EXISTS dim_projet (
    projet_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projet_code VARCHAR(100) NOT NULL UNIQUE,
    projet_nom VARCHAR(255) NOT NULL,
    ville VARCHAR(150) NOT NULL DEFAULT 'Pointe Noire',
    pays VARCHAR(150) NOT NULL DEFAULT 'Congo',
    devise VARCHAR(20) NOT NULL DEFAULT 'FCFA',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dim_lot (
    lot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot VARCHAR(255) NOT NULL UNIQUE,
    ordre_lot INTEGER NOT NULL DEFAULT 999,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dim_niveau (
    niveau_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    niveau VARCHAR(100) NOT NULL UNIQUE,
    ordre_niveau INTEGER NOT NULL DEFAULT 999,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dim_batiment (
    batiment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batiment VARCHAR(150) NOT NULL UNIQUE,
    type_batiment VARCHAR(100) NOT NULL DEFAULT 'A_CLASSER',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO dim_projet (projet_code, projet_nom, ville, pays, devise)
VALUES ('SP2I_DEFAULT', 'Centre medical Pointe Noire', 'Pointe Noire', 'Congo', 'FCFA')
ON CONFLICT (projet_code) DO UPDATE SET
    projet_nom = EXCLUDED.projet_nom,
    ville = EXCLUDED.ville,
    pays = EXCLUDED.pays,
    devise = EXCLUDED.devise,
    updated_at = now();

INSERT INTO dim_lot (lot, ordre_lot)
SELECT DISTINCT
    COALESCE(NULLIF(trim(lot), ''), 'NON_RENSEIGNE') AS lot,
    COALESCE(NULLIF(regexp_replace(COALESCE(lot, ''), '\D', '', 'g'), '')::INTEGER, 999) AS ordre_lot
FROM fact_metre
ON CONFLICT (lot) DO UPDATE SET
    ordre_lot = EXCLUDED.ordre_lot,
    updated_at = now();

INSERT INTO dim_niveau (niveau, ordre_niveau)
SELECT DISTINCT
    COALESCE(NULLIF(trim(niveau), ''), 'GLOBAL') AS niveau,
    CASE
        WHEN upper(COALESCE(niveau, '')) = 'GLOBAL' THEN 0
        WHEN upper(COALESCE(niveau, '')) = 'RDC' THEN 1
        WHEN upper(COALESCE(niveau, '')) LIKE 'ETAGE%' THEN
            10 + COALESCE(NULLIF(regexp_replace(niveau, '\D', '', 'g'), '')::INTEGER, 0)
        WHEN upper(COALESCE(niveau, '')) LIKE '%TERRASSE%' THEN 900
        ELSE 999
    END AS ordre_niveau
FROM fact_metre
ON CONFLICT (niveau) DO UPDATE SET
    ordre_niveau = EXCLUDED.ordre_niveau,
    updated_at = now();

INSERT INTO dim_batiment (batiment, type_batiment)
SELECT DISTINCT
    COALESCE(NULLIF(trim(batiment), ''), 'NON_RENSEIGNE') AS batiment,
    CASE
        WHEN lower(COALESCE(batiment, '')) LIKE '%annexe%' THEN 'ANNEXE'
        WHEN lower(COALESCE(batiment, '')) LIKE '%chantier%' THEN 'CHANTIER'
        WHEN trim(COALESCE(batiment, '')) = '' THEN 'NON_RENSEIGNE'
        ELSE 'BATIMENT_PRINCIPAL'
    END AS type_batiment
FROM fact_metre
ON CONFLICT (batiment) DO UPDATE SET
    type_batiment = EXCLUDED.type_batiment,
    updated_at = now();

/* -------------------------------------------------------------------------
3. ENRICHISSEMENT DE LA FACT TABLE SANS SUPPRIMER LES COLONNES EXISTANTES
--------------------------------------------------------------------------- */

ALTER TABLE fact_metre
    ADD COLUMN IF NOT EXISTS projet_id BIGINT,
    ADD COLUMN IF NOT EXISTS lot_id BIGINT,
    ADD COLUMN IF NOT EXISTS niveau_id BIGINT,
    ADD COLUMN IF NOT EXISTS batiment_id BIGINT,
    ADD COLUMN IF NOT EXISTS famille_id BIGINT,
    ADD COLUMN IF NOT EXISTS scenario_id BIGINT,
    ADD COLUMN IF NOT EXISTS pu_local DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS pu_import DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS capex_local DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS capex_import DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS economie DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS taux_economie DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS date_import TIMESTAMPTZ NOT NULL DEFAULT now();

UPDATE fact_metre f
SET
    projet_id = p.projet_id,
    lot_id = l.lot_id,
    niveau_id = n.niveau_id,
    batiment_id = b.batiment_id,
    famille_id = df.famille_id,
    pu_local = CASE WHEN COALESCE(f.quantite, 0) <> 0 THEN f.prix_total_ht / f.quantite ELSE 0 END,
    pu_import = COALESCE(f.pu_import, 0),
    capex_local = f.prix_total_ht,
    capex_import = COALESCE(NULLIF(f.capex_import, 0), CASE WHEN f.decision_import = 'IMPORT' THEN f.capex_optimise ELSE 0 END),
    economie = f.economie_nette,
    taux_economie = CASE WHEN COALESCE(f.prix_total_ht, 0) <> 0 THEN f.economie_nette / f.prix_total_ht ELSE 0 END,
    scenario_id = COALESCE(f.scenario_id, 1)
FROM dim_projet p, dim_lot l, dim_niveau n, dim_batiment b, dim_famille df
WHERE p.projet_code = 'SP2I_DEFAULT'
  AND l.lot = COALESCE(NULLIF(trim(f.lot), ''), 'NON_RENSEIGNE')
  AND n.niveau = COALESCE(NULLIF(trim(f.niveau), ''), 'GLOBAL')
  AND b.batiment = COALESCE(NULLIF(trim(f.batiment), ''), 'NON_RENSEIGNE')
  AND df.famille = COALESCE(NULLIF(trim(f.famille), ''), 'default');

/* -------------------------------------------------------------------------
4. TRIGGER DE COMPATIBILITE BACKEND

Le backend actuel continue a inserer lot/famille/batiment/niveau en texte.
Ce trigger cree les dimensions manquantes et renseigne les IDs automatiquement.
--------------------------------------------------------------------------- */

CREATE OR REPLACE FUNCTION sp2i_sync_star_schema_fact()
RETURNS TRIGGER AS $$
DECLARE
    v_projet_id BIGINT;
BEGIN
    INSERT INTO dim_projet (projet_code, projet_nom, ville, pays, devise)
    VALUES ('SP2I_DEFAULT', 'Centre medical Pointe Noire', 'Pointe Noire', 'Congo', 'FCFA')
    ON CONFLICT (projet_code) DO UPDATE SET updated_at = now()
    RETURNING projet_id INTO v_projet_id;

    NEW.projet_id := COALESCE(NEW.projet_id, v_projet_id);
    NEW.lot := COALESCE(NULLIF(trim(NEW.lot), ''), 'NON_RENSEIGNE');
    NEW.niveau := COALESCE(NULLIF(trim(NEW.niveau), ''), 'GLOBAL');
    NEW.batiment := COALESCE(NULLIF(trim(NEW.batiment), ''), 'NON_RENSEIGNE');
    NEW.famille := COALESCE(NULLIF(trim(NEW.famille), ''), 'default');

    INSERT INTO dim_lot (lot, ordre_lot)
    VALUES (NEW.lot, COALESCE(NULLIF(regexp_replace(NEW.lot, '\D', '', 'g'), '')::INTEGER, 999))
    ON CONFLICT (lot) DO UPDATE SET updated_at = now()
    RETURNING lot_id INTO NEW.lot_id;

    INSERT INTO dim_niveau (niveau, ordre_niveau)
    VALUES (
        NEW.niveau,
        CASE
            WHEN upper(NEW.niveau) = 'GLOBAL' THEN 0
            WHEN upper(NEW.niveau) = 'RDC' THEN 1
            WHEN upper(NEW.niveau) LIKE 'ETAGE%' THEN 10 + COALESCE(NULLIF(regexp_replace(NEW.niveau, '\D', '', 'g'), '')::INTEGER, 0)
            WHEN upper(NEW.niveau) LIKE '%TERRASSE%' THEN 900
            ELSE 999
        END
    )
    ON CONFLICT (niveau) DO UPDATE SET updated_at = now()
    RETURNING niveau_id INTO NEW.niveau_id;

    INSERT INTO dim_batiment (batiment, type_batiment)
    VALUES (
        NEW.batiment,
        CASE
            WHEN lower(NEW.batiment) LIKE '%annexe%' THEN 'ANNEXE'
            WHEN lower(NEW.batiment) LIKE '%chantier%' THEN 'CHANTIER'
            WHEN NEW.batiment = 'NON_RENSEIGNE' THEN 'NON_RENSEIGNE'
            ELSE 'BATIMENT_PRINCIPAL'
        END
    )
    ON CONFLICT (batiment) DO UPDATE SET updated_at = now()
    RETURNING batiment_id INTO NEW.batiment_id;

    INSERT INTO dim_famille (famille, libelle_famille, categorie_achat, categorie, importable, famille_id)
    VALUES (
        NEW.famille,
        initcap(replace(NEW.famille, '_', ' ')),
        'A_ANALYSER',
        'A_ANALYSER',
        FALSE,
        nextval('dim_famille_famille_id_seq')
    )
    ON CONFLICT (famille) DO UPDATE SET updated_at = now()
    RETURNING famille_id INTO NEW.famille_id;

    NEW.capex_local := COALESCE(NEW.capex_local, NEW.prix_total_ht, 0);
    NEW.economie := COALESCE(NEW.economie, NEW.economie_nette, 0);
    NEW.pu_local := COALESCE(NEW.pu_local, CASE WHEN COALESCE(NEW.quantite, 0) <> 0 THEN NEW.prix_total_ht / NEW.quantite ELSE 0 END);
    NEW.pu_import := COALESCE(NEW.pu_import, 0);
    NEW.capex_import := COALESCE(NEW.capex_import, CASE WHEN NEW.decision_import = 'IMPORT' THEN NEW.capex_optimise ELSE 0 END);
    NEW.taux_economie := COALESCE(NEW.taux_economie, CASE WHEN COALESCE(NEW.prix_total_ht, 0) <> 0 THEN NEW.economie_nette / NEW.prix_total_ht ELSE 0 END);
    NEW.scenario_id := COALESCE(NEW.scenario_id, 1);
    NEW.date_import := COALESCE(NEW.date_import, now());

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sp2i_sync_star_schema_fact ON fact_metre;
CREATE TRIGGER trg_sp2i_sync_star_schema_fact
BEFORE INSERT OR UPDATE ON fact_metre
FOR EACH ROW
EXECUTE FUNCTION sp2i_sync_star_schema_fact();

/* -------------------------------------------------------------------------
5. INDEXES ET CONTRAINTES POUR POWER BI
--------------------------------------------------------------------------- */

CREATE INDEX IF NOT EXISTS ix_fact_metre_projet_id ON fact_metre (projet_id);
CREATE INDEX IF NOT EXISTS ix_fact_metre_lot_id ON fact_metre (lot_id);
CREATE INDEX IF NOT EXISTS ix_fact_metre_niveau_id ON fact_metre (niveau_id);
CREATE INDEX IF NOT EXISTS ix_fact_metre_batiment_id ON fact_metre (batiment_id);
CREATE INDEX IF NOT EXISTS ix_fact_metre_famille_id ON fact_metre (famille_id);
CREATE INDEX IF NOT EXISTS ix_fact_metre_decision_import ON fact_metre (decision_import);
CREATE INDEX IF NOT EXISTS ix_fact_metre_date_import ON fact_metre (date_import);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_fact_metre_projet') THEN
        ALTER TABLE fact_metre
            ADD CONSTRAINT fk_fact_metre_projet
            FOREIGN KEY (projet_id) REFERENCES dim_projet(projet_id) NOT VALID;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_fact_metre_lot') THEN
        ALTER TABLE fact_metre
            ADD CONSTRAINT fk_fact_metre_lot
            FOREIGN KEY (lot_id) REFERENCES dim_lot(lot_id) NOT VALID;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_fact_metre_niveau') THEN
        ALTER TABLE fact_metre
            ADD CONSTRAINT fk_fact_metre_niveau
            FOREIGN KEY (niveau_id) REFERENCES dim_niveau(niveau_id) NOT VALID;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_fact_metre_batiment') THEN
        ALTER TABLE fact_metre
            ADD CONSTRAINT fk_fact_metre_batiment
            FOREIGN KEY (batiment_id) REFERENCES dim_batiment(batiment_id) NOT VALID;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_fact_metre_famille') THEN
        ALTER TABLE fact_metre
            ADD CONSTRAINT fk_fact_metre_famille
            FOREIGN KEY (famille_id) REFERENCES dim_famille(famille_id) NOT VALID;
    END IF;
END $$;

/* -------------------------------------------------------------------------
6. VUES KPI POUR POWER BI

Les vues exposent les mesures deja calculees. Power BI doit les charger comme
tables de reporting ou les utiliser pour controler les totaux.
--------------------------------------------------------------------------- */

DROP VIEW IF EXISTS
    v_kpi_capex,
    v_kpi_lot,
    v_kpi_famille,
    v_kpi_niveau,
    v_kpi_batiment,
    v_kpi_import_local,
    v_qualite_dqe;

CREATE OR REPLACE VIEW v_kpi_capex AS
SELECT
    COUNT(*) AS nombre_lignes,
    ROUND(COALESCE(SUM(capex_local), 0)::NUMERIC, 2) AS capex_local_total,
    ROUND(COALESCE(SUM(capex_import), 0)::NUMERIC, 2) AS capex_import_total,
    ROUND(COALESCE(SUM(capex_optimise), 0)::NUMERIC, 2) AS capex_optimise_total,
    ROUND(COALESCE(SUM(economie), 0)::NUMERIC, 2) AS economie_totale,
    ROUND(
        CASE WHEN COALESCE(SUM(capex_local), 0) = 0
            THEN 0
            ELSE (COALESCE(SUM(economie), 0)::NUMERIC / NULLIF(SUM(capex_local), 0)::NUMERIC) * 100
        END,
        2
    ) AS taux_economie_global
FROM fact_metre;

CREATE OR REPLACE VIEW v_kpi_lot AS
SELECT
    l.lot_id,
    l.lot,
    l.ordre_lot,
    COUNT(f.id_ligne) AS nombre_lignes,
    ROUND(COALESCE(SUM(f.capex_local), 0)::NUMERIC, 2) AS capex_local_total,
    ROUND(COALESCE(SUM(f.capex_import), 0)::NUMERIC, 2) AS capex_import_total,
    ROUND(COALESCE(SUM(f.capex_optimise), 0)::NUMERIC, 2) AS capex_optimise_total,
    ROUND(COALESCE(SUM(f.economie), 0)::NUMERIC, 2) AS economie_totale,
    ROUND(
        CASE WHEN COALESCE(SUM(f.capex_local), 0) = 0
            THEN 0
            ELSE (COALESCE(SUM(f.economie), 0)::NUMERIC / NULLIF(SUM(f.capex_local), 0)::NUMERIC) * 100
        END,
        2
    ) AS taux_economie
FROM dim_lot l
LEFT JOIN fact_metre f ON f.lot_id = l.lot_id
GROUP BY l.lot_id, l.lot, l.ordre_lot;

CREATE OR REPLACE VIEW v_kpi_famille AS
SELECT
    d.famille_id,
    d.famille,
    d.categorie,
    d.importable,
    COUNT(f.id_ligne) AS nombre_lignes,
    ROUND(COALESCE(SUM(f.capex_local), 0)::NUMERIC, 2) AS capex_local_total,
    ROUND(COALESCE(SUM(f.capex_import), 0)::NUMERIC, 2) AS capex_import_total,
    ROUND(COALESCE(SUM(f.capex_optimise), 0)::NUMERIC, 2) AS capex_optimise_total,
    ROUND(COALESCE(SUM(f.economie), 0)::NUMERIC, 2) AS economie_totale,
    ROUND(
        CASE WHEN COALESCE(SUM(f.capex_local), 0) = 0
            THEN 0
            ELSE (COALESCE(SUM(f.economie), 0)::NUMERIC / NULLIF(SUM(f.capex_local), 0)::NUMERIC) * 100
        END,
        2
    ) AS taux_economie
FROM dim_famille d
LEFT JOIN fact_metre f ON f.famille_id = d.famille_id
GROUP BY d.famille_id, d.famille, d.categorie, d.importable;

CREATE OR REPLACE VIEW v_kpi_niveau AS
SELECT
    n.niveau_id,
    n.niveau,
    n.ordre_niveau,
    COUNT(f.id_ligne) AS nombre_lignes,
    ROUND(COALESCE(SUM(f.capex_local), 0)::NUMERIC, 2) AS capex_local_total,
    ROUND(COALESCE(SUM(f.capex_import), 0)::NUMERIC, 2) AS capex_import_total,
    ROUND(COALESCE(SUM(f.capex_optimise), 0)::NUMERIC, 2) AS capex_optimise_total,
    ROUND(COALESCE(SUM(f.economie), 0)::NUMERIC, 2) AS economie_totale
FROM dim_niveau n
LEFT JOIN fact_metre f ON f.niveau_id = n.niveau_id
GROUP BY n.niveau_id, n.niveau, n.ordre_niveau;

CREATE OR REPLACE VIEW v_kpi_batiment AS
SELECT
    b.batiment_id,
    b.batiment,
    b.type_batiment,
    COUNT(f.id_ligne) AS nombre_lignes,
    ROUND(COALESCE(SUM(f.capex_local), 0)::NUMERIC, 2) AS capex_local_total,
    ROUND(COALESCE(SUM(f.capex_import), 0)::NUMERIC, 2) AS capex_import_total,
    ROUND(COALESCE(SUM(f.capex_optimise), 0)::NUMERIC, 2) AS capex_optimise_total,
    ROUND(COALESCE(SUM(f.economie), 0)::NUMERIC, 2) AS economie_totale
FROM dim_batiment b
LEFT JOIN fact_metre f ON f.batiment_id = b.batiment_id
GROUP BY b.batiment_id, b.batiment, b.type_batiment;

CREATE OR REPLACE VIEW v_kpi_import_local AS
SELECT
    decision_import,
    COUNT(*) AS nombre_lignes,
    ROUND(COALESCE(SUM(capex_local), 0)::NUMERIC, 2) AS capex_local_total,
    ROUND(COALESCE(SUM(capex_import), 0)::NUMERIC, 2) AS capex_import_total,
    ROUND(COALESCE(SUM(capex_optimise), 0)::NUMERIC, 2) AS capex_optimise_total,
    ROUND(COALESCE(SUM(economie), 0)::NUMERIC, 2) AS economie_totale
FROM fact_metre
GROUP BY decision_import;

CREATE OR REPLACE VIEW v_qualite_dqe AS
SELECT
    statut_ligne,
    COUNT(*) AS nombre_lignes,
    ROUND(COALESCE(SUM(capex_local), 0)::NUMERIC, 2) AS capex_local_total,
    ROUND((COUNT(*)::NUMERIC / NULLIF((SELECT COUNT(*) FROM fact_metre), 0)::NUMERIC), 4) AS part_lignes,
    CASE WHEN statut_ligne = 'OK' THEN 1 ELSE 0 END AS score_qualite_ligne
FROM fact_metre
GROUP BY statut_ligne;

COMMIT;
