/*
SP2I CAPEX - Decision Engine / Procurement Analytics

Objectif :
- ajouter les dimensions fournisseur, pays et niveau de risque ;
- historiser les scores decisionnels dans fact_simulation ;
- exposer des vues Power BI pretes pour l'analytics decisionnel.

Le script est idempotent.
*/

BEGIN;

CREATE TABLE IF NOT EXISTS dim_country (
    country_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_name VARCHAR(150) NOT NULL UNIQUE,
    customs_risk DOUBLE PRECISION NOT NULL DEFAULT 30,
    logistics_risk DOUBLE PRECISION NOT NULL DEFAULT 30,
    geopolitical_risk DOUBLE PRECISION NOT NULL DEFAULT 30,
    currency_risk DOUBLE PRECISION NOT NULL DEFAULT 30,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dim_supplier (
    supplier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name VARCHAR(255) NOT NULL UNIQUE,
    country_id BIGINT NULL REFERENCES dim_country(country_id),
    country VARCHAR(150) NOT NULL DEFAULT 'NON_RENSEIGNE',
    risk_score DOUBLE PRECISION NOT NULL DEFAULT 35,
    quality_score DOUBLE PRECISION NOT NULL DEFAULT 70,
    lead_time_avg DOUBLE PRECISION NOT NULL DEFAULT 35,
    delivery_score DOUBLE PRECISION NOT NULL DEFAULT 70,
    financial_score DOUBLE PRECISION NOT NULL DEFAULT 70,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dim_risk_level (
    risk_level VARCHAR(50) PRIMARY KEY,
    risk_weight DOUBLE PRECISION NOT NULL,
    risk_description TEXT NOT NULL DEFAULT ''
);

INSERT INTO dim_risk_level (risk_level, risk_weight, risk_description)
VALUES
    ('LOW', 10, 'Risque faible, import generalement acceptable.'),
    ('MEDIUM', 35, 'Risque moyen, arbitrage a documenter.'),
    ('HIGH', 65, 'Risque eleve, securisation necessaire.'),
    ('CRITICAL', 90, 'Risque critique, import a eviter sauf justification forte.')
ON CONFLICT (risk_level) DO UPDATE SET
    risk_weight = EXCLUDED.risk_weight,
    risk_description = EXCLUDED.risk_description;

INSERT INTO dim_country (country_name, customs_risk, logistics_risk, geopolitical_risk, currency_risk)
VALUES
    ('NON_RENSEIGNE', 30, 30, 30, 30),
    ('Chine', 35, 40, 30, 25),
    ('Congo', 10, 15, 20, 10),
    ('France', 15, 15, 10, 15)
ON CONFLICT (country_name) DO UPDATE SET
    customs_risk = EXCLUDED.customs_risk,
    logistics_risk = EXCLUDED.logistics_risk,
    geopolitical_risk = EXCLUDED.geopolitical_risk,
    currency_risk = EXCLUDED.currency_risk;

INSERT INTO dim_supplier (
    supplier_name,
    country_id,
    country,
    risk_score,
    quality_score,
    lead_time_avg,
    delivery_score,
    financial_score
)
SELECT
    'NON_RENSEIGNE',
    country_id,
    country_name,
    35,
    70,
    35,
    70,
    70
FROM dim_country
WHERE country_name = 'NON_RENSEIGNE'
ON CONFLICT (supplier_name) DO UPDATE SET
    country_id = EXCLUDED.country_id,
    country = EXCLUDED.country;

ALTER TABLE fact_simulation
    ADD COLUMN IF NOT EXISTS decision_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS risk_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS lead_time_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS criticality_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS decision_reason JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS decision_type VARCHAR(100) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS decision_confidence VARCHAR(50) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS supplier_id BIGINT NULL REFERENCES dim_supplier(supplier_id),
    ADD COLUMN IF NOT EXISTS country_id BIGINT NULL REFERENCES dim_country(country_id);

UPDATE fact_simulation f
SET
    supplier_id = COALESCE(f.supplier_id, s.supplier_id),
    country_id = COALESCE(f.country_id, s.country_id)
FROM dim_supplier s
WHERE s.supplier_name = 'NON_RENSEIGNE'
  AND (f.supplier_id IS NULL OR f.country_id IS NULL);

CREATE INDEX IF NOT EXISTS ix_fact_simulation_decision_score ON fact_simulation(decision_score);
CREATE INDEX IF NOT EXISTS ix_fact_simulation_decision_type ON fact_simulation(decision_type);
CREATE INDEX IF NOT EXISTS ix_fact_simulation_decision_confidence ON fact_simulation(decision_confidence);
CREATE INDEX IF NOT EXISTS ix_fact_simulation_supplier_id ON fact_simulation(supplier_id);
CREATE INDEX IF NOT EXISTS ix_fact_simulation_country_id ON fact_simulation(country_id);

DROP VIEW IF EXISTS
    v_decision_summary,
    v_decision_risk,
    v_supplier_performance,
    v_import_risk_analysis;

CREATE OR REPLACE VIEW v_decision_summary AS
SELECT
    s.scenario_id,
    s.scenario_nom,
    f.decision_type,
    f.decision_confidence,
    COUNT(*) AS nombre_lignes,
    ROUND(AVG(f.decision_score)::NUMERIC, 2) AS decision_score_moyen,
    ROUND(AVG(f.risk_score)::NUMERIC, 2) AS risk_score_moyen,
    ROUND(COALESCE(SUM(f.capex_local), 0)::NUMERIC, 2) AS capex_local_total,
    ROUND(COALESCE(SUM(f.capex_optimise), 0)::NUMERIC, 2) AS capex_optimise_total,
    ROUND(COALESCE(SUM(f.economie), 0)::NUMERIC, 2) AS economie_totale
FROM fact_simulation f
JOIN dim_scenario s ON s.scenario_id = f.scenario_id
GROUP BY s.scenario_id, s.scenario_nom, f.decision_type, f.decision_confidence;

CREATE OR REPLACE VIEW v_decision_risk AS
SELECT
    s.scenario_id,
    s.scenario_nom,
    f.decision_import,
    f.decision_type,
    CASE
        WHEN f.risk_score < 30 THEN 'LOW'
        WHEN f.risk_score < 60 THEN 'MEDIUM'
        WHEN f.risk_score < 80 THEN 'HIGH'
        ELSE 'CRITICAL'
    END AS risk_level,
    COUNT(*) AS nombre_lignes,
    ROUND(AVG(f.risk_score)::NUMERIC, 2) AS risk_score_moyen,
    ROUND(AVG(f.lead_time_score)::NUMERIC, 2) AS lead_time_score_moyen,
    ROUND(AVG(f.criticality_score)::NUMERIC, 2) AS criticality_score_moyen
FROM fact_simulation f
JOIN dim_scenario s ON s.scenario_id = f.scenario_id
GROUP BY s.scenario_id, s.scenario_nom, f.decision_import, f.decision_type, risk_level;

CREATE OR REPLACE VIEW v_supplier_performance AS
SELECT
    sp.supplier_id,
    sp.supplier_name,
    sp.country,
    COUNT(f.simulation_line_id) AS nombre_lignes,
    ROUND(AVG(f.decision_score)::NUMERIC, 2) AS decision_score_moyen,
    ROUND(AVG(f.risk_score)::NUMERIC, 2) AS risk_score_moyen,
    ROUND(COALESCE(SUM(f.economie), 0)::NUMERIC, 2) AS economie_totale,
    ROUND(AVG(sp.quality_score)::NUMERIC, 2) AS quality_score,
    ROUND(AVG(sp.delivery_score)::NUMERIC, 2) AS delivery_score,
    ROUND(AVG(sp.financial_score)::NUMERIC, 2) AS financial_score
FROM dim_supplier sp
LEFT JOIN fact_simulation f ON f.supplier_id = sp.supplier_id
GROUP BY sp.supplier_id, sp.supplier_name, sp.country;

CREATE OR REPLACE VIEW v_import_risk_analysis AS
SELECT
    c.country_name,
    COUNT(f.simulation_line_id) AS nombre_lignes,
    ROUND(AVG(f.risk_score)::NUMERIC, 2) AS risk_score_moyen,
    ROUND(AVG(c.customs_risk)::NUMERIC, 2) AS customs_risk,
    ROUND(AVG(c.logistics_risk)::NUMERIC, 2) AS logistics_risk,
    ROUND(AVG(c.geopolitical_risk)::NUMERIC, 2) AS geopolitical_risk,
    ROUND(AVG(c.currency_risk)::NUMERIC, 2) AS currency_risk,
    ROUND(COALESCE(SUM(f.economie), 0)::NUMERIC, 2) AS economie_totale
FROM dim_country c
LEFT JOIN fact_simulation f ON f.country_id = c.country_id
GROUP BY c.country_id, c.country_name;

COMMIT;
