/*
SP2I CAPEX - Container & Shipment Engine

Ajoute le socle logistique import Chine -> Pointe-Noire :
- dimensions containers ;
- tables shipments et couts logistiques ;
- champs logistiques dans fact_simulation ;
- vues Power BI pour containers, fret, livraison et fournisseurs.
*/

BEGIN;

CREATE TABLE IF NOT EXISTS dim_container (
    container_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    container_type VARCHAR(50) NOT NULL UNIQUE,
    max_volume DOUBLE PRECISION NOT NULL,
    max_weight DOUBLE PRECISION NOT NULL,
    container_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO dim_container (container_type, max_volume, max_weight, container_cost)
VALUES
    ('20FT', 33, 28000, 6500),
    ('40FT', 67, 26500, 12000),
    ('40HC', 76, 26500, 13500)
ON CONFLICT (container_type) DO UPDATE SET
    max_volume = EXCLUDED.max_volume,
    max_weight = EXCLUDED.max_weight,
    container_cost = EXCLUDED.container_cost;

CREATE TABLE IF NOT EXISTS fact_shipment (
    shipment_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    container_id BIGINT NULL REFERENCES dim_container(container_id),
    supplier_id BIGINT NULL REFERENCES dim_supplier(supplier_id),
    departure_port VARCHAR(150) NOT NULL DEFAULT 'Shanghai',
    arrival_port VARCHAR(150) NOT NULL DEFAULT 'Pointe-Noire',
    departure_date DATE NULL,
    arrival_date DATE NULL,
    shipment_status VARCHAR(50) NOT NULL DEFAULT 'READY',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS fact_logistics_cost (
    logistics_cost_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id UUID NULL REFERENCES fact_shipment(shipment_id),
    freight_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    customs_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    insurance_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    storage_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    delivery_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE fact_simulation
    ADD COLUMN IF NOT EXISTS container_strategy VARCHAR(50) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS shipment_strategy VARCHAR(100) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS fill_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS shipment_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS lead_time_total DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS storage_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS delivery_risk VARCHAR(50) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS logistics_reason JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE INDEX IF NOT EXISTS ix_fact_simulation_container_strategy ON fact_simulation(container_strategy);
CREATE INDEX IF NOT EXISTS ix_fact_simulation_shipment_strategy ON fact_simulation(shipment_strategy);
CREATE INDEX IF NOT EXISTS ix_fact_simulation_delivery_risk ON fact_simulation(delivery_risk);
CREATE INDEX IF NOT EXISTS ix_fact_simulation_fill_rate ON fact_simulation(fill_rate);

DROP VIEW IF EXISTS
    v_container_utilization,
    v_shipment_performance,
    v_logistics_costs,
    v_delivery_risk,
    v_supplier_logistics;

CREATE OR REPLACE VIEW v_container_utilization AS
SELECT
    s.scenario_id,
    s.scenario_nom,
    f.container_strategy,
    COUNT(*) AS nombre_lignes,
    ROUND(AVG(f.fill_rate)::NUMERIC, 4) AS fill_rate_moyen,
    ROUND(AVG(f.shipment_cost)::NUMERIC, 2) AS shipment_cost_moyen,
    ROUND(SUM(f.shipment_cost)::NUMERIC, 2) AS shipment_cost_total
FROM fact_simulation f
JOIN dim_scenario s ON s.scenario_id = f.scenario_id
GROUP BY s.scenario_id, s.scenario_nom, f.container_strategy;

CREATE OR REPLACE VIEW v_shipment_performance AS
SELECT
    s.scenario_id,
    s.scenario_nom,
    f.shipment_strategy,
    COUNT(*) AS nombre_lignes,
    ROUND(AVG(f.lead_time_total)::NUMERIC, 2) AS lead_time_total_moyen,
    ROUND(AVG(f.storage_cost)::NUMERIC, 2) AS storage_cost_moyen
FROM fact_simulation f
JOIN dim_scenario s ON s.scenario_id = f.scenario_id
GROUP BY s.scenario_id, s.scenario_nom, f.shipment_strategy;

CREATE OR REPLACE VIEW v_logistics_costs AS
SELECT
    s.scenario_id,
    s.scenario_nom,
    ROUND(SUM(f.shipment_cost)::NUMERIC, 2) AS shipment_cost_total,
    ROUND(SUM(f.storage_cost)::NUMERIC, 2) AS storage_cost_total,
    ROUND(AVG(f.fill_rate)::NUMERIC, 4) AS fill_rate_moyen,
    ROUND(AVG(f.lead_time_total)::NUMERIC, 2) AS lead_time_total_moyen
FROM fact_simulation f
JOIN dim_scenario s ON s.scenario_id = f.scenario_id
GROUP BY s.scenario_id, s.scenario_nom;

CREATE OR REPLACE VIEW v_delivery_risk AS
SELECT
    s.scenario_id,
    s.scenario_nom,
    f.delivery_risk,
    COUNT(*) AS nombre_lignes,
    ROUND(SUM(f.capex_optimise)::NUMERIC, 2) AS capex_expose,
    ROUND(AVG(f.lead_time_total)::NUMERIC, 2) AS lead_time_total_moyen
FROM fact_simulation f
JOIN dim_scenario s ON s.scenario_id = f.scenario_id
GROUP BY s.scenario_id, s.scenario_nom, f.delivery_risk;

CREATE OR REPLACE VIEW v_supplier_logistics AS
SELECT
    sp.supplier_id,
    sp.supplier_name,
    COUNT(f.simulation_line_id) AS nombre_lignes,
    ROUND(AVG(f.fill_rate)::NUMERIC, 4) AS fill_rate_moyen,
    ROUND(AVG(f.lead_time_total)::NUMERIC, 2) AS lead_time_total_moyen,
    ROUND(SUM(f.shipment_cost)::NUMERIC, 2) AS shipment_cost_total,
    ROUND(SUM(f.storage_cost)::NUMERIC, 2) AS storage_cost_total
FROM dim_supplier sp
LEFT JOIN fact_simulation f ON f.supplier_id = sp.supplier_id
GROUP BY sp.supplier_id, sp.supplier_name;

COMMIT;
