-- SP2I CAPEX - BIM_READY schema extension
-- Idempotent SQL for Neon/PostgreSQL.

CREATE TABLE IF NOT EXISTS dim_appartement (
    appartement_id VARCHAR(150) PRIMARY KEY,
    niveau_id VARCHAR(150) NOT NULL DEFAULT '',
    description VARCHAR(255) NOT NULL DEFAULT '',
    type VARCHAR(100) NOT NULL DEFAULT '',
    surface DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dim_piece (
    piece_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    piece_code VARCHAR(180) NOT NULL UNIQUE,
    batiment VARCHAR(150) NOT NULL DEFAULT '',
    niveau VARCHAR(100) NOT NULL DEFAULT '',
    appart VARCHAR(150) NOT NULL DEFAULT '',
    piece VARCHAR(150) NOT NULL DEFAULT '',
    type_piece VARCHAR(100) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE fact_metre
    ADD COLUMN IF NOT EXISTS appartement_id VARCHAR(150) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS piece_id BIGINT,
    ADD COLUMN IF NOT EXISTS piece_type VARCHAR(100) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS ifc_guid VARCHAR(150) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS ifc_type VARCHAR(150) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS bim_object VARCHAR(150) NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS ix_fact_metre_bim_scope
    ON fact_metre (batiment, niveau, appartement_id, piece, lot);

CREATE INDEX IF NOT EXISTS ix_fact_metre_ifc_guid
    ON fact_metre (ifc_guid);

CREATE OR REPLACE VIEW vw_bim_dashboard AS
SELECT
    COALESCE(project_code, projet_id::text, 'PROJET_MPEMBA') AS projet,
    COALESCE(batiment, 'NON_RENSEIGNE') AS batiment,
    COALESCE(niveau, 'GLOBAL') AS niveau,
    COALESCE(NULLIF(appartement_id, ''), NULLIF(appartement_code, ''), NULLIF(appart, ''), 'COMMUN') AS appartement,
    COALESCE(piece, 'NON_RENSEIGNE') AS piece,
    COALESCE(lot, 'NON_RENSEIGNE') AS lot,
    COALESCE(famille, 'default') AS famille,
    COALESCE(NULLIF(code_article, ''), NULLIF(article_id, ''), NULLIF(designation, ''), 'NON_RENSEIGNE') AS article,
    ROUND(COALESCE(SUM(COALESCE(capex_local, prix_total_ht, 0)), 0)::numeric, 2) AS capex_local,
    ROUND(COALESCE(SUM(COALESCE(capex_import, montant_import, 0)), 0)::numeric, 2) AS capex_import,
    ROUND(COALESCE(SUM(economie), 0)::numeric, 2) AS economie,
    COUNT(*) AS nb_lignes
FROM fact_metre
GROUP BY
    COALESCE(project_code, projet_id::text, 'PROJET_MPEMBA'),
    COALESCE(batiment, 'NON_RENSEIGNE'),
    COALESCE(niveau, 'GLOBAL'),
    COALESCE(NULLIF(appartement_id, ''), NULLIF(appartement_code, ''), NULLIF(appart, ''), 'COMMUN'),
    COALESCE(piece, 'NON_RENSEIGNE'),
    COALESCE(lot, 'NON_RENSEIGNE'),
    COALESCE(famille, 'default'),
    COALESCE(NULLIF(code_article, ''), NULLIF(article_id, ''), NULLIF(designation, ''), 'NON_RENSEIGNE');
