-- SP2I CAPEX - Phase 031 V6 Production Readiness
-- Mode parallele V5/V6: aucune vue V5 existante n'est remplacee.
-- Objets conserves:
-- - vw_bpu_v53_priced
-- - vw_fact_metre_current
-- - vw_fact_metre_financial_canonical

BEGIN;

CREATE TABLE IF NOT EXISTS dim_price_reference (
    price_reference_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_code VARCHAR(180) NOT NULL UNIQUE,
    lot_code VARCHAR(100) NOT NULL,
    scope_type VARCHAR(20) NOT NULL CHECK (scope_type IN ('ARTICLE', 'FAMILY', 'UNIT', 'LOT')),
    match_pattern TEXT NOT NULL,
    unite VARCHAR(50),
    famille VARCHAR(150),
    sous_lot VARCHAR(150),
    prix_local_fcfa NUMERIC(18, 2) NOT NULL CHECK (prix_local_fcfa > 0),
    prix_import_fcfa NUMERIC(18, 2) NOT NULL CHECK (prix_import_fcfa > 0),
    prix_optimise_fcfa NUMERIC(18, 2) NOT NULL CHECK (prix_optimise_fcfa > 0),
    source_prix VARCHAR(255) NOT NULL DEFAULT 'SP2I_V6_BUDGETARY_REFERENCE',
    niveau_confiance VARCHAR(50) NOT NULL DEFAULT 'BUDGETARY_TO_VALIDATE',
    price_priority INTEGER NOT NULL DEFAULT 100,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_dim_price_reference_lot_scope
    ON dim_price_reference (lot_code, scope_type, is_active);

CREATE INDEX IF NOT EXISTS ix_dim_price_reference_unite
    ON dim_price_reference (lot_code, unite, is_active);

CREATE TABLE IF NOT EXISTS dim_article_price_mapping (
    article_code VARCHAR(255) PRIMARY KEY,
    price_reference_code VARCHAR(180) NOT NULL REFERENCES dim_price_reference(reference_code),
    match_scope VARCHAR(20) NOT NULL CHECK (match_scope IN ('ARTICLE', 'FAMILY', 'UNIT', 'LOT')),
    match_confidence VARCHAR(50) NOT NULL DEFAULT 'AUTO_V6',
    mapping_source VARCHAR(255) NOT NULL DEFAULT 'AUTO_RULE_031',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_dim_article_price_mapping_reference
    ON dim_article_price_mapping (price_reference_code, is_active);

WITH seed(
    reference_code, lot_code, scope_type, match_pattern, unite, famille, sous_lot,
    prix_local_fcfa, prix_import_fcfa, prix_optimise_fcfa, niveau_confiance, price_priority
) AS (
    VALUES
    -- P0 / 029B: lots critiques recalibres.
    ('V6_GO_ACIER', 'LOT_GO', 'FAMILY', 'ACIER', 'KG', 'GROS_OEUVRE', 'ARMATURES', 1250, 1180, 1180, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_GO_COFFRAGE', 'LOT_GO', 'FAMILY', 'COFFRAGE', 'M2', 'GROS_OEUVRE', 'COFFRAGE', 28000, 28000, 28000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_GO_DALLE', 'LOT_GO', 'FAMILY', 'DALLE', 'M2', 'GROS_OEUVRE', 'DALLES', 52000, 52000, 52000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_GO_POUTRE', 'LOT_GO', 'FAMILY', 'POUTRE', 'ML', 'GROS_OEUVRE', 'POUTRES', 75000, 75000, 75000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_GO_POTEAU', 'LOT_GO', 'FAMILY', 'POTEAU', 'ML', 'GROS_OEUVRE', 'POTEAUX', 65000, 65000, 65000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_GO_BETON', 'LOT_GO', 'FAMILY', 'BETON', 'M3', 'GROS_OEUVRE', 'BETON', 115000, 115000, 115000, 'BUDGETARY_TO_VALIDATE', 20),

    ('V6_FACADE_CHEVILLES', 'LOT_FACADE', 'FAMILY', 'CHEVILLES', 'U', 'FACADE', 'FIXATIONS', 350, 280, 280, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_FACADE_OSSATURE', 'LOT_FACADE', 'FAMILY', 'OSSATURE', 'M2', 'FACADE', 'OSSATURE', 25000, 23000, 23000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_FACADE_ALUCOBOND', 'LOT_FACADE', 'FAMILY', 'ALUCOBOND', 'M2', 'FACADE', 'BARDAGE', 65000, 58000, 58000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_FACADE_ITE', 'LOT_FACADE', 'FAMILY', 'LAINE DE ROCHE', 'M2', 'FACADE', 'ISOLATION', 35000, 32000, 32000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_FACADE_COUVERTINES', 'LOT_FACADE', 'FAMILY', 'COUVERTINES', 'ML', 'FACADE', 'ACCESSOIRES', 45000, 40000, 40000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_FACADE_BAVETTES', 'LOT_FACADE', 'FAMILY', 'BAVETTES', 'ML', 'FACADE', 'ACCESSOIRES', 35000, 32000, 32000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_FACADE_HABILLAGES', 'LOT_FACADE', 'FAMILY', 'HABILLAGES', 'ENS', 'FACADE', 'FINITIONS', 5000000, 4800000, 4800000, 'BUDGETARY_TO_VALIDATE', 20),

    ('V6_MAC_ENDUIT_INTERIEUR', 'LOT_MAC', 'FAMILY', 'ENDUIT INTERIEUR', 'M2', 'MACONNERIE', 'ENDUITS', 8500, 8500, 8500, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_MAC_ENDUIT_EXTERIEUR', 'LOT_MAC', 'FAMILY', 'ENDUIT EXTERIEUR', 'M2', 'MACONNERIE', 'ENDUITS', 10500, 10500, 10500, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_MAC_BLOC_15', 'LOT_MAC', 'FAMILY', 'BLOC 15', 'M2', 'MACONNERIE', 'BLOCS', 18000, 18000, 18000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_MAC_BLOC_20', 'LOT_MAC', 'FAMILY', 'BLOC 20', 'M2', 'MACONNERIE', 'BLOCS', 22000, 22000, 22000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_MAC_CHAINAGE', 'LOT_MAC', 'FAMILY', 'CHAINAGE', 'ML', 'MACONNERIE', 'CHAINAGES', 18000, 18000, 18000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_MAC_MORTIER', 'LOT_MAC', 'FAMILY', 'MORTIER', 'M3', 'MACONNERIE', 'MORTIER', 95000, 95000, 95000, 'BUDGETARY_TO_VALIDATE', 20),

    ('V6_CVC_SPLIT_12000', 'LOT_CVC', 'FAMILY', 'SPLIT 12000', 'U', 'CVC', 'SPLIT', 650000, 590000, 590000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CVC_SPLIT_18000', 'LOT_CVC', 'FAMILY', 'SPLIT 18000', 'U', 'CVC', 'SPLIT', 850000, 780000, 780000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CVC_CUIVRE_LIQUIDE_12000', 'LOT_CVC', 'FAMILY', 'CUIVRE LIQUIDE SPLIT 12000', 'ML', 'CVC', 'LIAISONS_FRIGORIFIQUES', 35000, 32000, 32000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CVC_CUIVRE_LIQUIDE_18000', 'LOT_CVC', 'FAMILY', 'CUIVRE LIQUIDE SPLIT 18000', 'ML', 'CVC', 'LIAISONS_FRIGORIFIQUES', 40000, 36000, 36000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CVC_CUIVRE_GAZ_12000', 'LOT_CVC', 'FAMILY', 'CUIVRE GAZ SPLIT 12000', 'ML', 'CVC', 'LIAISONS_FRIGORIFIQUES', 38000, 35000, 35000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CVC_CUIVRE_GAZ_18000', 'LOT_CVC', 'FAMILY', 'CUIVRE GAZ SPLIT 18000', 'ML', 'CVC', 'LIAISONS_FRIGORIFIQUES', 43000, 39000, 39000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CVC_CONDENSAT_12000', 'LOT_CVC', 'FAMILY', 'CONDENSATS SPLIT 12000', 'ML', 'CVC', 'CONDENSATS', 12000, 11000, 11000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CVC_CONDENSAT_18000', 'LOT_CVC', 'FAMILY', 'CONDENSATS SPLIT 18000', 'ML', 'CVC', 'CONDENSATS', 14000, 13000, 13000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CVC_SUPPORT_12000', 'LOT_CVC', 'FAMILY', 'SUPPORT SPLIT 12000', 'U', 'CVC', 'ACCESSOIRES', 60000, 55000, 55000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CVC_SUPPORT_18000', 'LOT_CVC', 'FAMILY', 'SUPPORT SPLIT 18000', 'U', 'CVC', 'ACCESSOIRES', 75000, 69000, 69000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CVC_PERCEMENT_12000', 'LOT_CVC', 'FAMILY', 'PERCEMENT SPLIT 12000', 'U', 'CVC', 'POSE', 50000, 50000, 50000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CVC_PERCEMENT_18000', 'LOT_CVC', 'FAMILY', 'PERCEMENT SPLIT 18000', 'U', 'CVC', 'POSE', 60000, 60000, 60000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CVC_MES_12000', 'LOT_CVC', 'FAMILY', 'MISE EN SERVICE SPLIT 12000', 'U', 'CVC', 'MISE_EN_SERVICE', 100000, 100000, 100000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CVC_MES_18000', 'LOT_CVC', 'FAMILY', 'MISE EN SERVICE SPLIT 18000', 'U', 'CVC', 'MISE_EN_SERVICE', 120000, 120000, 120000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CVC_EXTRACTEUR', 'LOT_CVC', 'FAMILY', 'EXTRACTEUR', 'U', 'CVC', 'EXTRACTION', 350000, 320000, 320000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CVC_GAINE_EXTRACTEUR', 'LOT_CVC', 'FAMILY', 'GAINE EXTRACTEUR', 'ML', 'CVC', 'EXTRACTION', 35000, 32000, 32000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CVC_GRILLE_EXTRACTEUR', 'LOT_CVC', 'FAMILY', 'GRILLE EXTRACTEUR', 'U', 'CVC', 'EXTRACTION', 60000, 55000, 55000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CVC_CLAPET_EXTRACTEUR', 'LOT_CVC', 'FAMILY', 'CLAPET', 'U', 'CVC', 'EXTRACTION', 50000, 46000, 46000, 'BUDGETARY_TO_VALIDATE', 20),

    ('V6_ELEC_CABLE', 'LOT_ELEC', 'FAMILY', 'CABLE', 'ML', 'ELECTRICITE', 'CABLAGE', 7000, 6200, 6200, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_ELEC_GAINE', 'LOT_ELEC', 'FAMILY', 'GAINE', 'ML', 'ELECTRICITE', 'GAINES', 2500, 2200, 2200, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_ELEC_ALIMENTATION', 'LOT_ELEC', 'FAMILY', 'ALIMENTATION', 'ML', 'ELECTRICITE', 'CABLAGE', 5500, 5000, 5000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_ELEC_PRISE', 'LOT_ELEC', 'FAMILY', 'PRISE', 'U', 'ELECTRICITE', 'APPAREILLAGE', 15000, 13500, 13500, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_ELEC_BOITE', 'LOT_ELEC', 'FAMILY', 'BOITE', 'U', 'ELECTRICITE', 'APPAREILLAGE', 4500, 4000, 4000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_ELEC_CONNECTEUR', 'LOT_ELEC', 'FAMILY', 'CONNECTEUR', 'U', 'ELECTRICITE', 'ACCESSOIRES', 1500, 1300, 1300, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_ELEC_REPERAGE', 'LOT_ELEC', 'FAMILY', 'REPERAGE', 'U', 'ELECTRICITE', 'ACCESSOIRES', 1000, 1000, 1000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_ELEC_PROTECTION', 'LOT_ELEC', 'FAMILY', 'PROTECTION', 'U', 'ELECTRICITE', 'PROTECTIONS', 12000, 10800, 10800, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_ELEC_DISJONCTEUR', 'LOT_ELEC', 'FAMILY', 'DISJONCTEUR', 'U', 'ELECTRICITE', 'PROTECTIONS', 15000, 13500, 13500, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_ELEC_TABLEAU', 'LOT_ELEC', 'FAMILY', 'TABLEAU', 'U', 'ELECTRICITE', 'TABLEAUX', 50000, 45000, 45000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_ELEC_SPOT_LED', 'LOT_ELEC', 'FAMILY', 'SPOT LED', 'U', 'ELECTRICITE', 'ECLAIRAGE', 30000, 27000, 27000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_ELEC_DCL', 'LOT_ELEC', 'FAMILY', 'DCL', 'U', 'ELECTRICITE', 'ECLAIRAGE', 4500, 4000, 4000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_ELEC_DRIVER_LED', 'LOT_ELEC', 'FAMILY', 'DRIVER LED', 'U', 'ELECTRICITE', 'ECLAIRAGE', 15000, 13500, 13500, 'BUDGETARY_TO_VALIDATE', 20),

    -- P1: lots residuels majeurs.
    ('V6_TOIT_PRIMAIRE', 'LOT_TOIT', 'FAMILY', 'PRIMAIRE', 'M2', 'TOITURE', 'ETANCHEITE', 8000, 8000, 8000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_TOIT_MEMBRANE', 'LOT_TOIT', 'FAMILY', 'MEMBRANE', 'M2', 'TOITURE', 'ETANCHEITE', 26000, 26000, 26000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_TOIT_FORME_PENTE', 'LOT_TOIT', 'FAMILY', 'FORME DE PENTE', 'M2', 'TOITURE', 'PENTE', 28000, 28000, 28000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_TOIT_ISOLATION', 'LOT_TOIT', 'FAMILY', 'ISOLATION', 'M2', 'TOITURE', 'ISOLATION', 24000, 24000, 24000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_TOIT_PROTECTION', 'LOT_TOIT', 'FAMILY', 'PROTECTION', 'M2', 'TOITURE', 'PROTECTION', 18000, 18000, 18000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_TOIT_RELEVES', 'LOT_TOIT', 'FAMILY', 'RELEVES', 'ML', 'TOITURE', 'ACROTERES', 22000, 22000, 22000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_TOIT_DESCENTES_EP', 'LOT_TOIT', 'FAMILY', 'DESCENTES', 'ML', 'TOITURE', 'EP', 26000, 26000, 26000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_TOIT_NAISSANCES_EP', 'LOT_TOIT', 'FAMILY', 'NAISSANCES', 'U', 'TOITURE', 'EP', 45000, 45000, 45000, 'BUDGETARY_TO_VALIDATE', 20),

    ('V6_FP_PLAQUE_BA13', 'LOT_FP', 'FAMILY', 'PLAQUE BA13', 'M2', 'FAUX_PLAFOND', 'PLAQUES', 8500, 8500, 8500, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_FP_OSSATURE', 'LOT_FP', 'FAMILY', 'OSSATURE', 'M2', 'FAUX_PLAFOND', 'OSSATURE', 5500, 5500, 5500, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_FP_FOURRURES', 'LOT_FP', 'FAMILY', 'FOURRURES', 'ML', 'FAUX_PLAFOND', 'OSSATURE', 2800, 2800, 2800, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_FP_SUSPENTES', 'LOT_FP', 'FAMILY', 'SUSPENTES', 'U', 'FAUX_PLAFOND', 'ACCESSOIRES', 1200, 1200, 1200, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_FP_BANDES', 'LOT_FP', 'FAMILY', 'BANDES', 'ML', 'FAUX_PLAFOND', 'JOINTS', 1500, 1500, 1500, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_FP_ENDUITS', 'LOT_FP', 'FAMILY', 'ENDUITS', 'KG', 'FAUX_PLAFOND', 'ENDUITS', 3000, 3000, 3000, 'BUDGETARY_TO_VALIDATE', 20),

    ('V6_MENU_EXT_VITRAGE', 'LOT_MENU_EXT', 'FAMILY', 'VITRAGE', 'M2', 'MENUISERIE_EXT', 'VITRAGE', 55000, 52000, 52000, 'LOW_BUDGETARY_TO_VALIDATE', 20),
    ('V6_MENU_EXT_FENETRES', 'LOT_MENU_EXT', 'FAMILY', 'FENETRES', 'U', 'MENUISERIE_EXT', 'ALUMINIUM', 250000, 230000, 230000, 'LOW_BUDGETARY_TO_VALIDATE', 20),
    ('V6_MENU_EXT_BAIES', 'LOT_MENU_EXT', 'FAMILY', 'BAIES', 'U', 'MENUISERIE_EXT', 'ALUMINIUM', 450000, 420000, 420000, 'LOW_BUDGETARY_TO_VALIDATE', 20),
    ('V6_MENU_EXT_PORTES', 'LOT_MENU_EXT', 'FAMILY', 'PORTES', 'U', 'MENUISERIE_EXT', 'PORTES', 350000, 330000, 330000, 'LOW_BUDGETARY_TO_VALIDATE', 20),
    ('V6_MENU_EXT_QUINCAILLERIE', 'LOT_MENU_EXT', 'FAMILY', 'QUINCAILLERIE', 'ENS', 'MENUISERIE_EXT', 'ACCESSOIRES', 3000000, 2800000, 2800000, 'LOW_BUDGETARY_TO_VALIDATE', 20),

    ('V6_PNT_IMPRESSION', 'LOT_PNT', 'FAMILY', 'IMPRESSION', 'M2', 'PEINTURE', 'IMPRESSION', 2500, 2500, 2500, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_PNT_MURS', 'LOT_PNT', 'FAMILY', 'PEINTURE MURS', 'M2', 'PEINTURE', 'MURS', 4500, 4500, 4500, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_PNT_PLAFOND', 'LOT_PNT', 'FAMILY', 'PEINTURE PLAFOND', 'M2', 'PEINTURE', 'PLAFOND', 5000, 5000, 5000, 'BUDGETARY_TO_VALIDATE', 20),

    ('V6_VRD_VOIRIE', 'LOT_VRD', 'FAMILY', 'VOIRIE', 'M2', 'VRD', 'VOIRIE', 25000, 25000, 25000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_VRD_EP', 'LOT_VRD', 'FAMILY', 'EAUX PLUVIALES', 'ML', 'VRD', 'EP', 25000, 25000, 25000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_VRD_EU', 'LOT_VRD', 'FAMILY', 'EAUX USEES', 'ML', 'VRD', 'EU', 28000, 28000, 28000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_VRD_CANIVEAUX', 'LOT_VRD', 'FAMILY', 'CANIVEAUX', 'ML', 'VRD', 'CANIVEAUX', 35000, 35000, 35000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_VRD_ECLAIRAGE', 'LOT_VRD', 'FAMILY', 'ECLAIRAGE', 'U', 'VRD', 'ECLAIRAGE', 120000, 110000, 110000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_VRD_REGARDS', 'LOT_VRD', 'FAMILY', 'REGARDS', 'U', 'VRD', 'REGARDS', 150000, 140000, 140000, 'BUDGETARY_TO_VALIDATE', 20),

    -- P2: lots restants de second ordre.
    ('V6_ASC_CABINE', 'LOT_ASC', 'FAMILY', 'CABINE', 'U', 'ASCENSEUR', 'CABINE', 8000000, 7500000, 7500000, 'LOW_BUDGETARY_TO_VALIDATE', 20),
    ('V6_ASC_MOTEUR', 'LOT_ASC', 'FAMILY', 'MOTEUR', 'U', 'ASCENSEUR', 'MACHINE', 6500000, 6100000, 6100000, 'LOW_BUDGETARY_TO_VALIDATE', 20),
    ('V6_ASC_ARMOIRE', 'LOT_ASC', 'FAMILY', 'ARMOIRE', 'U', 'ASCENSEUR', 'COMMANDE', 3500000, 3300000, 3300000, 'LOW_BUDGETARY_TO_VALIDATE', 20),
    ('V6_ASC_PORTES', 'LOT_ASC', 'FAMILY', 'PORTES', 'U', 'ASCENSEUR', 'PORTES', 900000, 850000, 850000, 'LOW_BUDGETARY_TO_VALIDATE', 20),
    ('V6_ASC_GUIDAGE', 'LOT_ASC', 'FAMILY', 'GUIDAGE', 'ENS', 'ASCENSEUR', 'GUIDAGE', 2500000, 2350000, 2350000, 'LOW_BUDGETARY_TO_VALIDATE', 20),
    ('V6_ASC_TELEALARME', 'LOT_ASC', 'FAMILY', 'TELEALARME', 'U', 'ASCENSEUR', 'SECURITE', 800000, 760000, 760000, 'LOW_BUDGETARY_TO_VALIDATE', 20),
    ('V6_ASC_ESSAIS', 'LOT_ASC', 'FAMILY', 'ESSAIS', 'ENS', 'ASCENSEUR', 'MISE_EN_SERVICE', 2500000, 2500000, 2500000, 'LOW_BUDGETARY_TO_VALIDATE', 20),

    ('V6_SAN_LAVABO', 'LOT_SAN', 'FAMILY', 'LAVABO', 'U', 'SANITAIRE', 'APPAREILS', 75000, 70000, 70000, 'LOW_BUDGETARY_TO_VALIDATE', 20),
    ('V6_SAN_DOUCHE', 'LOT_SAN', 'FAMILY', 'DOUCHE', 'U', 'SANITAIRE', 'APPAREILS', 180000, 170000, 170000, 'LOW_BUDGETARY_TO_VALIDATE', 20),
    ('V6_SAN_WC', 'LOT_SAN', 'FAMILY', 'WC', 'U', 'SANITAIRE', 'APPAREILS', 140000, 130000, 130000, 'LOW_BUDGETARY_TO_VALIDATE', 20),
    ('V6_SAN_PAROI', 'LOT_SAN', 'FAMILY', 'PAROI', 'U', 'SANITAIRE', 'APPAREILS', 180000, 170000, 170000, 'LOW_BUDGETARY_TO_VALIDATE', 20),
    ('V6_SAN_JOINT', 'LOT_SAN', 'FAMILY', 'JOINT', 'U', 'SANITAIRE', 'JOINTS', 3500, 3500, 3500, 'LOW_BUDGETARY_TO_VALIDATE', 20),
    ('V6_SAN_FIXATION', 'LOT_SAN', 'FAMILY', 'FIXATION', 'U', 'SANITAIRE', 'FIXATIONS', 5000, 5000, 5000, 'LOW_BUDGETARY_TO_VALIDATE', 20),
    ('V6_SAN_SIPHON', 'LOT_SAN', 'FAMILY', 'SIPHON', 'U', 'SANITAIRE', 'SIPHONS', 15000, 14000, 14000, 'LOW_BUDGETARY_TO_VALIDATE', 20),
    ('V6_SAN_ROBINET', 'LOT_SAN', 'FAMILY', 'ROBINET', 'U', 'SANITAIRE', 'ROBINETTERIE', 35000, 32000, 32000, 'LOW_BUDGETARY_TO_VALIDATE', 20),
    ('V6_SAN_MITIGEUR', 'LOT_SAN', 'FAMILY', 'MITIGEUR', 'U', 'SANITAIRE', 'ROBINETTERIE', 65000, 60000, 60000, 'LOW_BUDGETARY_TO_VALIDATE', 20),
    ('V6_SAN_ETANCHEITE', 'LOT_SAN', 'FAMILY', 'ETANCHEITE', 'ENS', 'SANITAIRE', 'ETANCHEITE', 45000, 45000, 45000, 'LOW_BUDGETARY_TO_VALIDATE', 20),

    ('V6_CFA_CAT6', 'LOT_CFA', 'FAMILY', 'CAT6', 'ML', 'CFA', 'CABLAGE', 2500, 2200, 2200, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CFA_COAXIAL', 'LOT_CFA', 'FAMILY', 'COAXIAL', 'ML', 'CFA', 'CABLAGE', 1800, 1600, 1600, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CFA_GAINE', 'LOT_CFA', 'FAMILY', 'GAINE', 'ML', 'CFA', 'GAINES', 700, 650, 650, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CFA_RJ45', 'LOT_CFA', 'FAMILY', 'RJ45', 'U', 'CFA', 'APPAREILLAGE', 12000, 11000, 11000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CFA_PRISE_TV', 'LOT_CFA', 'FAMILY', 'PRISE TV', 'U', 'CFA', 'APPAREILLAGE', 10000, 9000, 9000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CFA_BOITE', 'LOT_CFA', 'FAMILY', 'BOITE', 'U', 'CFA', 'APPAREILLAGE', 3000, 2700, 2700, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CFA_REPERAGE', 'LOT_CFA', 'FAMILY', 'REPERAGE', 'U', 'CFA', 'ACCESSOIRES', 800, 800, 800, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CFA_PATCH', 'LOT_CFA', 'FAMILY', 'PATCH', 'U', 'CFA', 'ACTIFS', 45000, 42000, 42000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CFA_SWITCH', 'LOT_CFA', 'FAMILY', 'SWITCH', 'U', 'CFA', 'ACTIFS', 120000, 110000, 110000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CFA_REPARTITEUR', 'LOT_CFA', 'FAMILY', 'REPARTITEUR', 'U', 'CFA', 'ACTIFS', 35000, 32000, 32000, 'BUDGETARY_TO_VALIDATE', 20),

    ('V6_CAR_CARRELAGE', 'LOT_CAR', 'FAMILY', 'CARRELAGE', 'M2', 'CARRELAGE', 'REVETEMENT', 18000, 17000, 17000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CAR_COLLE', 'LOT_CAR', 'FAMILY', 'COLLE', 'KG', 'CARRELAGE', 'COLLE', 1800, 1700, 1700, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CAR_JOINT', 'LOT_CAR', 'FAMILY', 'JOINT', 'KG', 'CARRELAGE', 'JOINTS', 2500, 2400, 2400, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CAR_PLINTHE', 'LOT_CAR', 'FAMILY', 'PLINTHE', 'ML', 'CARRELAGE', 'PLINTHES', 4500, 4200, 4200, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_CAR_ETANCHEITE', 'LOT_CAR', 'FAMILY', 'ETANCHEITE', 'M2', 'CARRELAGE', 'ETANCHEITE', 12000, 12000, 12000, 'BUDGETARY_TO_VALIDATE', 20),

    ('V6_PLOMB_ALIMENTATION', 'LOT_PLOMB', 'FAMILY', 'ALIMENTATION', 'ML', 'PLOMBERIE', 'EF_EC', 6500, 6000, 6000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_PLOMB_EVACUATION', 'LOT_PLOMB', 'FAMILY', 'EVACUATION', 'ML', 'PLOMBERIE', 'EVACUATION', 7500, 7000, 7000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_PLOMB_RACCORDS', 'LOT_PLOMB', 'FAMILY', 'RACCORDS', 'U', 'PLOMBERIE', 'RACCORDS', 2500, 2300, 2300, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_PLOMB_ROBINET', 'LOT_PLOMB', 'FAMILY', 'ROBINET', 'U', 'PLOMBERIE', 'ROBINETTERIE', 18000, 16000, 16000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_PLOMB_SIPHON', 'LOT_PLOMB', 'FAMILY', 'SIPHON', 'U', 'PLOMBERIE', 'SIPHONS', 12000, 11000, 11000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_PLOMB_FIXATION', 'LOT_PLOMB', 'FAMILY', 'FIXATION', 'U', 'PLOMBERIE', 'FIXATIONS', 3000, 2800, 2800, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_PLOMB_EVIER', 'LOT_PLOMB', 'FAMILY', 'EVIER', 'U', 'PLOMBERIE', 'APPAREIL', 85000, 80000, 80000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_PLOMB_JOINT', 'LOT_PLOMB', 'FAMILY', 'JOINT', 'U', 'PLOMBERIE', 'JOINTS', 2000, 2000, 2000, 'BUDGETARY_TO_VALIDATE', 20),

    -- P3: suppression du fallback restant.
    ('V6_INCENDIE_DETECTEUR', 'LOT_INCENDIE', 'FAMILY', 'DETECTEURS', 'U', 'INCENDIE', 'DETECTION', 35000, 32000, 32000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_INCENDIE_BAES', 'LOT_INCENDIE', 'FAMILY', 'BLOCS', 'U', 'INCENDIE', 'BAES', 45000, 42000, 42000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_INCENDIE_EXTINCTEUR', 'LOT_INCENDIE', 'FAMILY', 'EXTINCTEURS', 'U', 'INCENDIE', 'EXTINCTEURS', 60000, 55000, 55000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_INCENDIE_RIA', 'LOT_INCENDIE', 'FAMILY', 'ROBINETS', 'U', 'INCENDIE', 'RIA', 250000, 230000, 230000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_INCENDIE_CMSI', 'LOT_INCENDIE', 'FAMILY', 'CENTRALISATEUR', 'U', 'INCENDIE', 'CMSI', 450000, 420000, 420000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_INCENDIE_SIGNALISATION', 'LOT_INCENDIE', 'FAMILY', 'SIGNALISATION', 'ENS', 'INCENDIE', 'SIGNALISATION', 250000, 250000, 250000, 'BUDGETARY_TO_VALIDATE', 20),

    ('V6_MENU_INT_PORTES_SDB', 'LOT_MENU_INT', 'FAMILY', 'PORTES SALLES DE BAIN', 'U', 'MENUISERIE_INT', 'PORTES', 90000, 85000, 85000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_MENU_INT_PORTES_CHAMBRES', 'LOT_MENU_INT', 'FAMILY', 'PORTES CHAMBRES', 'U', 'MENUISERIE_INT', 'PORTES', 95000, 90000, 90000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_MENU_INT_PORTES_TECH', 'LOT_MENU_INT', 'FAMILY', 'PORTES TECHNIQUES', 'U', 'MENUISERIE_INT', 'PORTES', 140000, 130000, 130000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_MENU_INT_DRESSING', 'LOT_MENU_INT', 'FAMILY', 'DRESSING', 'ENS', 'MENUISERIE_INT', 'DRESSING', 350000, 330000, 330000, 'BUDGETARY_TO_VALIDATE', 20),

    ('V6_SECURITE_CAMERA', 'LOT_SECURITE', 'FAMILY', 'CAMERAS', 'U', 'SECURITE', 'VIDEO', 75000, 70000, 70000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_SECURITE_CONTROLE_ACCES', 'LOT_SECURITE', 'FAMILY', 'CONTROLE ACCES', 'U', 'SECURITE', 'ACCES', 180000, 165000, 165000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_SECURITE_NVR', 'LOT_SECURITE', 'FAMILY', 'ENREGISTREUR', 'U', 'SECURITE', 'VIDEO', 350000, 320000, 320000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_SECURITE_INTRUSION', 'LOT_SECURITE', 'FAMILY', 'INTRUSION', 'ENS', 'SECURITE', 'INTRUSION', 750000, 700000, 700000, 'BUDGETARY_TO_VALIDATE', 20),
    ('V6_SECURITE_INTERPHONIE', 'LOT_SECURITE', 'FAMILY', 'INTERPHONIE', 'ENS', 'SECURITE', 'INTERPHONIE', 600000, 550000, 550000, 'BUDGETARY_TO_VALIDATE', 20)
)
INSERT INTO dim_price_reference (
    reference_code, lot_code, scope_type, match_pattern, unite, famille, sous_lot,
    prix_local_fcfa, prix_import_fcfa, prix_optimise_fcfa, source_prix, niveau_confiance, price_priority
)
SELECT
    reference_code, lot_code, scope_type, match_pattern, unite, famille, sous_lot,
    prix_local_fcfa, prix_import_fcfa, prix_optimise_fcfa,
    'SP2I_V6_BUDGETARY_REFERENCE',
    niveau_confiance,
    price_priority
FROM seed
ON CONFLICT (reference_code) DO UPDATE SET
    lot_code = EXCLUDED.lot_code,
    scope_type = EXCLUDED.scope_type,
    match_pattern = EXCLUDED.match_pattern,
    unite = EXCLUDED.unite,
    famille = EXCLUDED.famille,
    sous_lot = EXCLUDED.sous_lot,
    prix_local_fcfa = EXCLUDED.prix_local_fcfa,
    prix_import_fcfa = EXCLUDED.prix_import_fcfa,
    prix_optimise_fcfa = EXCLUDED.prix_optimise_fcfa,
    source_prix = EXCLUDED.source_prix,
    niveau_confiance = EXCLUDED.niveau_confiance,
    price_priority = EXCLUDED.price_priority,
    is_active = TRUE,
    updated_at = now();

INSERT INTO dim_article_price_mapping (
    article_code,
    price_reference_code,
    match_scope,
    match_confidence,
    mapping_source,
    is_active
)
WITH normalized_bpu AS (
    SELECT
        b.article_code,
        b.lot_code,
        UPPER(TRIM(regexp_replace(b.designation, '[[:space:]]+-[[:space:]]+ligne DQE[[:space:]]+[0-9]+[[:space:]]*$', '', 'i'))) AS designation_norm,
        UPPER(TRIM(COALESCE(b.unite, ''))) AS unite_norm
    FROM dim_bpu_v53 b
),
ranked_matches AS (
    SELECT
        b.article_code,
        r.reference_code,
        r.scope_type,
        CASE
            WHEN r.scope_type = 'ARTICLE' THEN 'AUTO_EXACT_ARTICLE_V6'
            WHEN r.scope_type = 'FAMILY' THEN 'AUTO_FAMILY_V6'
            WHEN r.scope_type = 'UNIT' THEN 'AUTO_UNIT_V6'
            ELSE 'AUTO_LOT_V6'
        END AS match_confidence,
        ROW_NUMBER() OVER (
            PARTITION BY b.article_code
            ORDER BY
                CASE r.scope_type
                    WHEN 'ARTICLE' THEN 1
                    WHEN 'FAMILY' THEN 2
                    WHEN 'UNIT' THEN 3
                    WHEN 'LOT' THEN 4
                    ELSE 9
                END,
                r.price_priority,
                LENGTH(r.match_pattern) DESC,
                r.reference_code
        ) AS rn
    FROM normalized_bpu b
    JOIN dim_price_reference r
      ON r.is_active = TRUE
     AND r.lot_code = b.lot_code
     AND (
        (r.scope_type = 'ARTICLE'
            AND b.designation_norm = UPPER(TRIM(r.match_pattern))
            AND (r.unite IS NULL OR UPPER(TRIM(r.unite)) = b.unite_norm))
        OR
        (r.scope_type = 'FAMILY'
            AND b.designation_norm LIKE '%' || UPPER(TRIM(r.match_pattern)) || '%'
            AND (r.unite IS NULL OR UPPER(TRIM(r.unite)) = b.unite_norm))
        OR
        (r.scope_type = 'UNIT'
            AND UPPER(TRIM(r.unite)) = b.unite_norm)
        OR
        (r.scope_type = 'LOT')
     )
)
SELECT
    article_code,
    reference_code,
    scope_type,
    match_confidence,
    'AUTO_RULE_031',
    TRUE
FROM ranked_matches
WHERE rn = 1
ON CONFLICT (article_code) DO UPDATE SET
    price_reference_code = EXCLUDED.price_reference_code,
    match_scope = EXCLUDED.match_scope,
    match_confidence = EXCLUDED.match_confidence,
    mapping_source = EXCLUDED.mapping_source,
    is_active = TRUE,
    updated_at = now();

CREATE OR REPLACE VIEW vw_bpu_v53_priced_v2 AS
SELECT
    b.article_code,
    b.designation,
    b.lot_code,
    b.sous_lot_code,
    b.unite,
    COALESCE(r.prix_local_fcfa, legacy.prix_local_fcfa)::numeric AS prix_local_fcfa,
    COALESCE(r.prix_import_fcfa, legacy.prix_import_fcfa)::numeric AS prix_import_fcfa,
    COALESCE(r.prix_optimise_fcfa, legacy.prix_optimise_fcfa)::numeric AS prix_optimise_fcfa,
    GREATEST(
        COALESCE(r.prix_local_fcfa, legacy.prix_local_fcfa)
        - COALESCE(r.prix_optimise_fcfa, legacy.prix_optimise_fcfa),
        0
    )::numeric AS economie_unitaire_fcfa,
    CASE
        WHEN COALESCE(r.prix_import_fcfa, legacy.prix_import_fcfa)
             < COALESCE(r.prix_local_fcfa, legacy.prix_local_fcfa)
        THEN 'IMPORT'
        ELSE 'LOCAL'
    END AS decision_import,
    b.fournisseur_local,
    b.fournisseur_import,
    b.pays_import,
    COALESCE(r.source_prix, legacy.source_prix)::varchar(255) AS source_prix,
    b.date_reference,
    COALESCE(r.niveau_confiance, legacy.niveau_confiance)::text AS niveau_confiance,
    m.price_reference_code,
    COALESCE(m.match_scope, 'LEGACY_LOT_FALLBACK')::text AS pricing_scope,
    COALESCE(m.match_confidence, 'LEGACY_017')::text AS pricing_confidence,
    legacy.coefficient_import,
    legacy.coefficient_transport,
    legacy.coefficient_douane,
    legacy.coefficient_logistique,
    legacy.coefficient_global_import,
    legacy.prix_base_local_fcfa,
    legacy.prix_base_import_fcfa,
    b.is_active
FROM dim_bpu_v53 b
JOIN vw_bpu_v53_priced legacy
  ON legacy.article_code = b.article_code
LEFT JOIN dim_article_price_mapping m
  ON m.article_code = b.article_code
 AND m.is_active = TRUE
LEFT JOIN dim_price_reference r
  ON r.reference_code = m.price_reference_code
 AND r.is_active = TRUE;

CREATE OR REPLACE VIEW vw_project_cost_summary AS
WITH direct_cost AS (
    SELECT
        SUM(c.quantite * p.prix_local_fcfa)::numeric AS capex_direct,
        SUM(c.quantite * p.prix_import_fcfa)::numeric AS capex_import,
        SUM(c.quantite * p.prix_optimise_fcfa)::numeric AS capex_optimise,
        COUNT(*) FILTER (WHERE p.pricing_scope = 'LEGACY_LOT_FALLBACK') AS fallback_legacy_lot_lines,
        SUM(c.quantite * p.prix_local_fcfa) FILTER (WHERE p.pricing_scope = 'LEGACY_LOT_FALLBACK')::numeric AS fallback_legacy_lot_capex
    FROM vw_fact_metre_financial_canonical c
    JOIN vw_bpu_v53_priced_v2 p
      ON p.article_code = c.article_code
),
rates AS (
    SELECT
        0.1100::numeric AS indirect_rate,
        0.0420::numeric AS site_installation_rate,
        0.0350::numeric AS import_logistics_rate,
        0.1200::numeric AS contingency_rate,
        1263.90::numeric AS surface_m2,
        6::numeric AS nb_appartements,
        3::numeric AS nb_niveaux
),
base AS (
    SELECT
        d.capex_direct,
        d.capex_import,
        d.capex_optimise,
        COALESCE(d.fallback_legacy_lot_lines, 0) AS fallback_legacy_lot_lines,
        COALESCE(d.fallback_legacy_lot_capex, 0) AS fallback_legacy_lot_capex,
        ROUND(d.capex_direct * r.indirect_rate, 2) AS indirect_costs,
        ROUND(d.capex_direct * r.site_installation_rate, 2) AS site_installation,
        ROUND(d.capex_direct * r.import_logistics_rate, 2) AS import_logistics,
        r.contingency_rate,
        r.surface_m2,
        r.nb_appartements,
        r.nb_niveaux
    FROM direct_cost d
    CROSS JOIN rates r
)
SELECT
    capex_direct,
    indirect_costs,
    site_installation,
    import_logistics,
    ROUND((capex_direct + indirect_costs + site_installation + import_logistics) * contingency_rate, 2) AS contingency,
    ROUND(
        (capex_direct + indirect_costs + site_installation + import_logistics)
        * (1 + contingency_rate),
        2
    ) AS total_project_cost,
    surface_m2,
    ROUND(capex_direct / NULLIF(surface_m2, 0), 2) AS capex_direct_per_m2,
    ROUND(
        ((capex_direct + indirect_costs + site_installation + import_logistics) * (1 + contingency_rate))
        / NULLIF(surface_m2, 0),
        2
    ) AS total_project_cost_per_m2,
    nb_appartements,
    ROUND(
        ((capex_direct + indirect_costs + site_installation + import_logistics) * (1 + contingency_rate))
        / NULLIF(nb_appartements, 0),
        2
    ) AS total_project_cost_per_appartement,
    nb_niveaux,
    ROUND(
        ((capex_direct + indirect_costs + site_installation + import_logistics) * (1 + contingency_rate))
        / NULLIF(nb_niveaux, 0),
        2
    ) AS total_project_cost_per_niveau,
    capex_import,
    capex_optimise,
    fallback_legacy_lot_lines,
    fallback_legacy_lot_capex,
    ROUND(100.0 * fallback_legacy_lot_capex / NULLIF(capex_direct, 0), 2) AS fallback_legacy_lot_pct
FROM base;

CREATE OR REPLACE VIEW vw_dashboard_direction_v6 AS
WITH by_lot AS (
    SELECT
        c.lot,
        SUM(c.quantite * p.prix_local_fcfa)::numeric AS capex_direct,
        COUNT(*) AS nb_lignes,
        COUNT(DISTINCT c.article_code) AS nb_articles,
        COUNT(*) FILTER (WHERE p.pricing_scope = 'LEGACY_LOT_FALLBACK') AS fallback_legacy_lot_lines,
        SUM(c.quantite * p.prix_local_fcfa) FILTER (WHERE p.pricing_scope = 'LEGACY_LOT_FALLBACK')::numeric AS fallback_legacy_lot_capex
    FROM vw_fact_metre_financial_canonical c
    JOIN vw_bpu_v53_priced_v2 p
      ON p.article_code = c.article_code
    GROUP BY c.lot
),
total AS (
    SELECT SUM(capex_direct) AS total_capex_direct
    FROM by_lot
)
SELECT
    b.lot,
    b.capex_direct,
    ROUND(100.0 * b.capex_direct / NULLIF(t.total_capex_direct, 0), 2) AS pct_capex_direct,
    b.nb_lignes,
    b.nb_articles,
    b.fallback_legacy_lot_lines,
    COALESCE(b.fallback_legacy_lot_capex, 0) AS fallback_legacy_lot_capex,
    p.capex_direct AS project_capex_direct,
    p.indirect_costs,
    p.site_installation,
    p.import_logistics,
    p.contingency,
    p.total_project_cost,
    p.total_project_cost_per_m2,
    p.total_project_cost_per_appartement,
    p.total_project_cost_per_niveau
FROM by_lot b
CROSS JOIN total t
CROSS JOIN vw_project_cost_summary p
ORDER BY b.capex_direct DESC;

CREATE OR REPLACE VIEW vw_cost_intelligence_v6 AS
SELECT
    c.lot,
    c.sous_lot,
    c.article_code,
    c.designation,
    c.unite,
    SUM(c.quantite)::numeric AS quantite,
    MIN(p.prix_local_fcfa)::numeric AS prix_local_fcfa,
    MIN(p.prix_import_fcfa)::numeric AS prix_import_fcfa,
    MIN(p.prix_optimise_fcfa)::numeric AS prix_optimise_fcfa,
    SUM(c.quantite * p.prix_local_fcfa)::numeric AS capex_local,
    SUM(c.quantite * p.prix_import_fcfa)::numeric AS capex_import,
    SUM(c.quantite * p.prix_optimise_fcfa)::numeric AS capex_optimise,
    SUM(c.quantite * (p.prix_local_fcfa - p.prix_optimise_fcfa))::numeric AS economie,
    MIN(p.decision_import)::text AS decision_import,
    MIN(p.pricing_scope)::text AS pricing_scope,
    MIN(p.pricing_confidence)::text AS pricing_confidence,
    MIN(p.price_reference_code)::text AS price_reference_code
FROM vw_fact_metre_financial_canonical c
JOIN vw_bpu_v53_priced_v2 p
  ON p.article_code = c.article_code
GROUP BY
    c.lot,
    c.sous_lot,
    c.article_code,
    c.designation,
    c.unite;

COMMENT ON VIEW vw_bpu_v53_priced_v2 IS
'V6 parallel pricing view. Keeps V5 pricing intact and exposes article/family/unit pricing for financial V6.';

COMMENT ON VIEW vw_project_cost_summary IS
'V6 Total Project Cost summary: CAPEX direct, indirects, site installation, import logistics, contingency and investor KPIs.';

COMMENT ON VIEW vw_dashboard_direction_v6 IS
'V6 Direction cockpit view. Parallel to V5 dashboards; does not replace existing Power BI views.';

COMMENT ON VIEW vw_cost_intelligence_v6 IS
'V6 Cost Intelligence view using vw_bpu_v53_priced_v2. Parallel to vw_cost_intelligence.';

COMMIT;
