import {
  AlertTriangle,
  BarChart3,
  Bell,
  Boxes,
  Building2,
  CircleDollarSign,
  Clock3,
  Database,
  FileSpreadsheet,
  GitCompare,
  Gauge,
  LayoutGrid,
  Home,
  PackageSearch,
  Play,
  Route,
  Settings,
  Ship,
  SlidersHorizontal,
  Target,
  Truck,
  Upload,
  Users,
  Workflow,
} from "lucide-react";

export const sidebarQuickActions = [
  { label: "Importer DQE", path: "/app/dqe?tab=import", icon: Upload },
  { label: "Simulation", path: "/app/simulation", icon: Play },
  { label: "Nouveau scenario", path: "/app/simulation?tab=scenarios", icon: GitCompare },
];

export const sidebarSections = [
  {
    id: "direction",
    title: "Cockpit Direction",
    icon: Home,
    badge: "Live",
    items: [
      { label: "Dashboard global", path: "/app", icon: Gauge },
      { label: "KPIs", path: "/app/analytics?dashboard=direction", icon: BarChart3 },
      { label: "CAPEX", path: "/app/analytics?dashboard=capex", icon: CircleDollarSign },
      { label: "ROI", path: "/app/simulation?tab=compare", icon: Target },
      { label: "Cashflow", path: "/app/procurement?tab=cashflow", icon: CircleDollarSign },
      { label: "Alertes", path: "/app/analytics?dashboard=risks", icon: Bell, badge: "3" },
    ],
  },
  {
    id: "site",
    title: "Chantier & Planning",
    icon: Building2,
    items: [
      { label: "Planning", path: "/app/site?tab=planning", icon: Clock3 },
      { label: "Avancement", path: "/app/site?tab=criticality", icon: Workflow },
      { label: "Dependances", path: "/app/site?tab=dependencies", icon: Route },
      { label: "Logistique chantier", path: "/app/site?tab=deliveries", icon: Truck },
    ],
  },
  {
    id: "procurement",
    title: "Import & Procurement",
    icon: PackageSearch,
    items: [
      { label: "Optimisation import", path: "/app/procurement?tab=import", icon: Ship },
      { label: "Fournisseurs", path: "/app/procurement?tab=suppliers", icon: Users },
      { label: "Containers", path: "/app/logistics?tab=containers", icon: Boxes },
      { label: "Couts logistiques", path: "/app/logistics?tab=freight", icon: Truck },
      { label: "Risques import", path: "/app/procurement?tab=risks", icon: AlertTriangle },
    ],
  },
  {
    id: "analytics",
    title: "Analytics",
    icon: BarChart3,
    items: [
      { label: "Heatmaps", path: "/app/analytics?dashboard=heatmaps", icon: LayoutGrid },
      { label: "Drill-down", path: "/app/analytics?dashboard=drilldown", icon: Route },
      { label: "Risk matrix", path: "/app/analytics?dashboard=risks", icon: AlertTriangle },
      { label: "Timeline", path: "/app/analytics?dashboard=timeline", icon: Clock3 },
      { label: "Dashboards", path: "/app/analytics?dashboard=direction", icon: BarChart3 },
    ],
  },
  {
    id: "dqe",
    title: "Donnees & DQE",
    icon: FileSpreadsheet,
    items: [
      { label: "Upload DQE", path: "/app/dqe?tab=import", icon: Upload },
      { label: "Analyse IA", path: "/app/dqe?tab=analysis", icon: Database },
      { label: "Synchronisation", path: "/app/dqe?tab=import", icon: GitCompare },
      { label: "Qualite donnees", path: "/app/dqe?tab=quality", icon: BarChart3 },
      { label: "Historique imports", path: "/app/dqe?tab=analysis", icon: Clock3 },
    ],
  },
  {
    id: "settings",
    title: "Parametres",
    icon: Settings,
    items: [
      { label: "Parametres CAPEX", path: "/app/simulation?tab=simulation", icon: SlidersHorizontal },
      { label: "Taux import", path: "/app/procurement?tab=import", icon: CircleDollarSign },
      { label: "Configuration", path: "/app/analytics?dashboard=admin", icon: Settings },
      { label: "Monitoring", path: "/app/analytics?dashboard=monitoring", icon: Gauge },
      { label: "Utilisateurs", path: "/app/analytics?dashboard=users", icon: Users },
    ],
  },
];
