from __future__ import annotations

from typing import Any


DQE_ISSUE_CATEGORIES = {
    "FILE_STRUCTURE",
    "SHEET_DETECTION",
    "SCHEMA",
    "NUMERIC_VALUE",
    "LINE_CLASSIFICATION",
    "BUSINESS_CLASSIFICATION",
    "REFERENTIAL",
    "CAPEX_CONSISTENCY",
    "SYNC",
    "GOVERNANCE",
    "WORKFLOW",
}

DQE_ISSUE_SEVERITIES = {
    "DATA_LOSS",
    "DATA_INTEGRITY",
    "DATA_QUALITY",
    "REVIEW_REQUIRED",
    "WARNING",
    "SYNC_REQUIRED",
    "STALE",
}


ISSUE_DEFINITIONS: dict[str, dict[str, Any]] = {
    "FILE_EMPTY": {
        "category": "FILE_STRUCTURE",
        "severity": "DATA_LOSS",
        "blocking": True,
        "message": "Le fichier Excel ne contient aucune donnee exploitable.",
        "impact": "Aucune ligne DQE ne peut alimenter le budget, les scenarios ou l'approvisionnement.",
        "manual_fix": "Ouvrez le fichier Excel et verifiez qu'il contient bien une feuille de metre avec des lignes d'articles.",
        "example": "Ajouter une feuille METRE avec DESIGNATION, QUANTITE, UNITE et PU_LOCAL.",
    },
    "DQE_SHEET_NOT_FOUND": {
        "category": "SHEET_DETECTION",
        "severity": "DATA_INTEGRITY",
        "blocking": True,
        "message": "Aucune feuille candidate DQE n'a ete detectee.",
        "impact": "SP2I ne peut pas identifier la source metier a analyser.",
        "manual_fix": "Renommez la feuille contenant le metre en METRE ou DQE, ou verifiez que les colonnes d'articles sont presentes dans une feuille lisible.",
        "example": "Renommer la feuille 'Feuil1' en 'METRE'.",
    },
    "WRONG_SHEET_SELECTED": {
        "category": "SHEET_DETECTION",
        "severity": "REVIEW_REQUIRED",
        "blocking": False,
        "message": "La feuille retenue semble ne pas contenir le DQE principal.",
        "impact": "Les lignes normalisees peuvent venir d'une feuille de recapitulatif ou de parametres.",
        "manual_fix": "Verifiez que la feuille contenant les colonnes Designation, Quantite, Unite et Prix est bien identifiable. Renommez-la en METRE si necessaire.",
        "example": "Utiliser METRE pour la feuille detaillee et RECAP_LOTS pour la synthese.",
    },
    "HEADER_NOT_FOUND": {
        "category": "SCHEMA",
        "severity": "DATA_INTEGRITY",
        "blocking": True,
        "message": "La ligne d'en-tete n'a pas pu etre identifiee.",
        "impact": "Les colonnes metier ne peuvent pas etre associees aux champs SP2I.",
        "manual_fix": "Ajoutez une ligne d'en-tete claire avec les colonnes CODE_BPU, DESIGNATION, UNITE, QUANTITE, PU_LOCAL ou MONTANT_LOCAL.",
        "example": "Placer les en-tetes sur la premiere ligne de la feuille METRE.",
    },
    "MISSING_REQUIRED_COLUMN": {
        "category": "SCHEMA",
        "severity": "DATA_INTEGRITY",
        "blocking": True,
        "message": "Une colonne obligatoire est absente.",
        "impact": "SP2I ne peut pas calculer toutes les lignes article de facon fiable.",
        "manual_fix": "Ajoutez ou renommez la colonne manquante avec un des alias acceptes.",
        "example": "Renommer 'Qte article' en 'QUANTITE'.",
    },
    "RECOMMENDED_COLUMN_MISSING": {
        "category": "SCHEMA",
        "severity": "DATA_QUALITY",
        "blocking": False,
        "message": "Une colonne recommandee est absente.",
        "impact": "L'analyse reste possible mais certains regroupements seront moins precis.",
        "manual_fix": "Ajoutez cette colonne pour ameliorer les analyses par lot, famille, niveau ou batiment.",
        "example": "Ajouter une colonne LOT pour les corps d'etat.",
    },
    "AMBIGUOUS_COLUMN_ALIAS": {
        "category": "SCHEMA",
        "severity": "REVIEW_REQUIRED",
        "blocking": False,
        "message": "Un libelle de colonne est ambigu.",
        "impact": "Le prix local, import ou global peut etre mal interprete sans validation.",
        "manual_fix": "Renommez la colonne ambigue en PU_LOCAL, PU_IMPORT ou PU_ESTIME_LOCAL_FCFA pour lever l'ambiguite.",
        "example": "Remplacer 'PU' par 'PU_LOCAL'.",
    },
    "FORBIDDEN_PRICE_MAPPING": {
        "category": "SCHEMA",
        "severity": "DATA_INTEGRITY",
        "blocking": True,
        "message": "CODE_BPU ne doit jamais etre utilise comme prix.",
        "impact": "Un identifiant article utilise comme prix fausse le CAPEX et les scenarios.",
        "manual_fix": "Verifiez que CODE_BPU reste un identifiant article. Le prix doit etre dans une colonne PU_LOCAL, PU_ESTIME_LOCAL_FCFA ou MONTANT_LOCAL.",
        "example": "CODE_BPU = ELEC-001, PU_LOCAL = 125000.",
    },
    "EMPTY_QUANTITY": {
        "category": "NUMERIC_VALUE",
        "severity": "REVIEW_REQUIRED",
        "blocking": False,
        "message": "Une ligne article a une designation mais pas de quantite.",
        "impact": "Le montant de cette ligne ne peut pas etre verifie ligne par ligne.",
        "manual_fix": "Renseignez la quantite dans la ligne Excel concernee ou confirmez que la ligne ne doit pas etre prise en compte.",
        "example": "Ajouter 12 dans la colonne QUANTITE.",
    },
    "ZERO_QUANTITY": {
        "category": "NUMERIC_VALUE",
        "severity": "REVIEW_REQUIRED",
        "blocking": False,
        "message": "Une ligne article a une quantite egale a zero.",
        "impact": "La ligne peut etre exclue des montants ou signaler un poste non chiffre.",
        "manual_fix": "Verifiez si la quantite zero est volontaire. Si non, corrigez la quantite dans Excel.",
        "example": "Remplacer 0 par la quantite prevue.",
    },
    "NEGATIVE_QUANTITY": {
        "category": "NUMERIC_VALUE",
        "severity": "DATA_INTEGRITY",
        "blocking": True,
        "message": "Une quantite negative a ete detectee.",
        "impact": "Une quantite negative inverse les montants et rend le budget incoherent.",
        "manual_fix": "Corrigez la quantite negative. Une quantite d'article doit etre positive.",
        "example": "Remplacer -5 par 5 si c'est une erreur de saisie.",
    },
    "EMPTY_PRICE": {
        "category": "NUMERIC_VALUE",
        "severity": "REVIEW_REQUIRED",
        "blocking": False,
        "message": "Le prix unitaire ou le montant est absent.",
        "impact": "Le CAPEX local ne peut pas etre calcule pour cette ligne sans hypothese.",
        "manual_fix": "Renseignez un prix unitaire local ou un montant total pour permettre le calcul CAPEX.",
        "example": "Ajouter PU_LOCAL ou MONTANT_LOCAL.",
    },
    "ZERO_PRICE": {
        "category": "NUMERIC_VALUE",
        "severity": "REVIEW_REQUIRED",
        "blocking": False,
        "message": "Un prix nul a ete detecte.",
        "impact": "Le budget peut etre sous-estime si le prix zero n'est pas volontaire.",
        "manual_fix": "Verifiez si le prix zero est volontaire. Si non, renseignez le prix unitaire ou le montant total.",
        "example": "Remplacer 0 par le prix fournisseur.",
    },
    "NEGATIVE_PRICE": {
        "category": "NUMERIC_VALUE",
        "severity": "DATA_INTEGRITY",
        "blocking": True,
        "message": "Un prix negatif a ete detecte.",
        "impact": "Un prix negatif diminue artificiellement le budget et les gains.",
        "manual_fix": "Corrigez le prix negatif. Un prix d'article doit etre positif.",
        "example": "Remplacer -125000 par 125000.",
    },
    "AMOUNT_MISMATCH": {
        "category": "CAPEX_CONSISTENCY",
        "severity": "REVIEW_REQUIRED",
        "blocking": False,
        "message": "Le montant total ne correspond pas a quantite x prix unitaire.",
        "impact": "La ligne peut produire un ecart entre le DQE, le budget et les scenarios.",
        "manual_fix": "Verifiez la quantite, le prix unitaire ou le montant total. Corrigez la valeur incoherente dans Excel.",
        "example": "Si QTE=10 et PU=5000, le montant attendu est 50000.",
    },
    "INVALID_NUMERIC_FORMAT": {
        "category": "NUMERIC_VALUE",
        "severity": "DATA_INTEGRITY",
        "blocking": True,
        "message": "Un nombre semble mal formate ou impossible a interpreter.",
        "impact": "SP2I peut lire une valeur differente de celle attendue.",
        "manual_fix": "Uniformisez le format numerique : utilisez des nombres sans texte, par exemple 1200500 ou 1 200 500 selon le format accepte.",
        "example": "Remplacer '1.200.500 FCFA' par '1200500'.",
    },
    "MIXED_CURRENCY": {
        "category": "NUMERIC_VALUE",
        "severity": "REVIEW_REQUIRED",
        "blocking": False,
        "message": "Plusieurs devises semblent presentes dans une meme colonne.",
        "impact": "Les montants ne sont pas comparables sans conversion explicite.",
        "manual_fix": "Separez les montants par devise ou convertissez tous les prix dans la devise du projet.",
        "example": "Mettre les prix locaux en FCFA et les prix import en USD dans des colonnes separees.",
    },
    "STRUCTURAL_ROW_IGNORED": {
        "category": "LINE_CLASSIFICATION",
        "severity": "WARNING",
        "blocking": False,
        "message": "Une ligne structurelle a ete ignoree.",
        "impact": "Aucun impact negatif : cette ligne n'est pas un article et ne doit pas alimenter les calculs.",
        "manual_fix": "Aucune correction obligatoire. Cette ligne est ignoree car elle correspond a une structure du fichier et non a un article.",
        "example": "Titre de lot, sous-total, total ou ligne vide.",
    },
    "ARTICLE_LINE_NOT_NORMALIZED": {
        "category": "LINE_CLASSIFICATION",
        "severity": "DATA_LOSS",
        "blocking": True,
        "message": "Une vraie ligne article semble ne pas avoir ete normalisee.",
        "impact": "Le budget et les scenarios peuvent perdre une ligne metier.",
        "manual_fix": "Completez les champs obligatoires de cette ligne : designation, quantite et prix ou montant.",
        "example": "Renseigner DESIGNATION, QUANTITE et PU_LOCAL.",
    },
    "DUPLICATE_ARTICLE_LINE": {
        "category": "LINE_CLASSIFICATION",
        "severity": "REVIEW_REQUIRED",
        "blocking": False,
        "message": "Une ligne article semble dupliquee.",
        "impact": "Le budget peut etre surestime si le doublon est involontaire.",
        "manual_fix": "Verifiez si la ligne est reellement un doublon. Supprimez-la ou modifiez-la si elle correspond a un autre poste.",
        "example": "Deux lignes identiques avec meme lot, designation, quantite et prix.",
    },
    "MISSING_LOT": {
        "category": "BUSINESS_CLASSIFICATION",
        "severity": "DATA_QUALITY",
        "blocking": False,
        "message": "Une ligne ne contient pas de lot explicite.",
        "impact": "L'analyse par corps d'etat sera moins fiable.",
        "manual_fix": "Ajoutez une colonne LOT ou renseignez le lot correspondant pour ameliorer l'analyse par corps d'etat.",
        "example": "L07 - ELECTRICITE.",
    },
    "MISSING_FAMILY": {
        "category": "BUSINESS_CLASSIFICATION",
        "severity": "DATA_QUALITY",
        "blocking": False,
        "message": "La famille article est absente.",
        "impact": "La classification achat repose uniquement sur le mapping automatique.",
        "manual_fix": "Ajoutez une colonne FAMILLE ou verifiez le mapping automatique des familles.",
        "example": "FAMILLE = ELECTRICITE.",
    },
    "UNKNOWN_BPU_CODE": {
        "category": "REFERENTIAL",
        "severity": "REVIEW_REQUIRED",
        "blocking": False,
        "message": "Un code BPU n'est pas reconnu dans le referentiel.",
        "impact": "Le rattachement fournisseur ou prix de reference peut etre incomplet.",
        "manual_fix": "Ajoutez ce code au referentiel BPU ou corrigez le code dans le DQE.",
        "example": "Verifier CODE_BPU = ELEC-001.",
    },
    "UNKNOWN_UNIT": {
        "category": "REFERENTIAL",
        "severity": "DATA_QUALITY",
        "blocking": False,
        "message": "Une unite inconnue ou non normalisee a ete detectee.",
        "impact": "Les comparaisons de prix par unite peuvent etre degradees.",
        "manual_fix": "Remplacez l'unite par une valeur standard : U, M2, M3, ML, KG, ENS, etc.",
        "example": "Remplacer 'metre carre' par 'm2'.",
    },
    "UNKNOWN_LOT": {
        "category": "REFERENTIAL",
        "severity": "DATA_QUALITY",
        "blocking": False,
        "message": "Un lot n'est pas reconnu.",
        "impact": "Les analyses par lot peuvent etre moins fiables.",
        "manual_fix": "Corrigez le nom du lot ou ajoutez-le au referentiel des lots.",
        "example": "Utiliser L01 - GROS OEUVRE ET DEMOLITION.",
    },
    "CAPEX_LOCAL_NOT_COMPUTABLE": {
        "category": "CAPEX_CONSISTENCY",
        "severity": "DATA_INTEGRITY",
        "blocking": True,
        "message": "Le CAPEX local est impossible a calculer.",
        "impact": "La ligne ne peut pas alimenter le budget local ni les scenarios.",
        "manual_fix": "Verifiez que la ligne possede une quantite et un prix local ou un montant total.",
        "example": "Ajouter QUANTITE et PU_LOCAL.",
    },
    "ABNORMAL_SAVINGS_RATE": {
        "category": "CAPEX_CONSISTENCY",
        "severity": "REVIEW_REQUIRED",
        "blocking": False,
        "message": "Le taux d'economie semble anormal.",
        "impact": "Une erreur d'unite, de devise ou de prix peut fausser la decision achat.",
        "manual_fix": "Verifiez les prix local/import, les unites et les quantites. Une erreur d'unite peut expliquer cet ecart.",
        "example": "Controler les lignes avec economie > 80% ou < -50%.",
    },
    "LINE_AMOUNT_OUTLIER": {
        "category": "CAPEX_CONSISTENCY",
        "severity": "REVIEW_REQUIRED",
        "blocking": False,
        "message": "Le montant de la ligne est atypique par rapport aux autres lignes.",
        "impact": "Un montant extreme peut fausser les KPI et les arbitrages.",
        "manual_fix": "Verifiez si le montant est coherent avec l'unite et la quantite.",
        "example": "Controler une ligne 10x superieure a la mediane de sa famille.",
    },
    "SYNC_PARTIAL": {
        "category": "SYNC",
        "severity": "SYNC_REQUIRED",
        "blocking": False,
        "message": "La synchronisation est partielle.",
        "impact": "Toutes les lignes normalisees ne sont pas presentes dans FACT_METRE.",
        "manual_fix": "Relancez la synchronisation. Si le probleme persiste, verifiez les lignes rejetees dans le rapport d'audit.",
        "example": "584 lignes normalisees mais 500 synchronisees.",
    },
    "SYNC_FAILED": {
        "category": "SYNC",
        "severity": "SYNC_REQUIRED",
        "blocking": False,
        "message": "La synchronisation budget a echoue.",
        "impact": "Les scenarios et le workflow budget restent bloques.",
        "manual_fix": "Relancez la synchronisation du budget. Si l'erreur persiste, verifiez la connexion base de donnees et les logs backend.",
        "example": "Erreur PostgreSQL pendant l'insertion FACT_METRE.",
    },
    "FACT_EMPTY_AFTER_SYNC": {
        "category": "SYNC",
        "severity": "DATA_LOSS",
        "blocking": True,
        "message": "FACT_METRE est vide apres synchronisation.",
        "impact": "Le budget synchronise ne contient aucune ligne exploitable.",
        "manual_fix": "Relancez la synchronisation et verifiez que les lignes normalisees sont bien envoyees dans FACT_METRE.",
        "example": "Verifier le mapping quantite/prix avant synchronisation.",
    },
    "AUDIT_METRICS_INCONSISTENT": {
        "category": "GOVERNANCE",
        "severity": "DATA_INTEGRITY",
        "blocking": True,
        "message": "Les metriques d'audit DQE sont incoherentes.",
        "impact": "Le workflow peut afficher un DQE certifie avec des compteurs a zero.",
        "manual_fix": "Relancez l'analyse DQE. Si le probleme persiste, verifiez la table d'audit DQE et les metriques historisees.",
        "example": "CERTIFIED avec trust_score=0 ou normalized_lines_count=0.",
    },
    "MULTIPLE_ACTIVE_DQE": {
        "category": "WORKFLOW",
        "severity": "DATA_INTEGRITY",
        "blocking": True,
        "message": "Plusieurs versions DQE actives sont detectees.",
        "impact": "Le workflow ne peut pas determiner une source unique de verite.",
        "manual_fix": "Desactivez les anciennes versions DQE et conservez une seule version active.",
        "example": "Une seule version doit avoir is_active=true.",
    },
    "DQE_STALE_FOR_SCENARIO": {
        "category": "WORKFLOW",
        "severity": "STALE",
        "blocking": False,
        "message": "Le scenario semble base sur un ancien DQE.",
        "impact": "Les arbitrages CAPEX peuvent ne pas refleter le dernier budget importe.",
        "manual_fix": "Relancez la simulation CAPEX a partir du DQE actif le plus recent.",
        "example": "Scenario cree avant le dernier import DQE.",
    },
}


def validate_issue_catalog() -> list[str]:
    errors: list[str] = []
    required = {"category", "severity", "blocking", "message", "impact", "manual_fix"}
    for issue_type, definition in ISSUE_DEFINITIONS.items():
        missing = sorted(required - set(definition))
        if missing:
            errors.append(f"{issue_type}: champs manquants {', '.join(missing)}")
        if definition.get("category") not in DQE_ISSUE_CATEGORIES:
            errors.append(f"{issue_type}: categorie inconnue {definition.get('category')}")
        if definition.get("severity") not in DQE_ISSUE_SEVERITIES:
            errors.append(f"{issue_type}: gravite inconnue {definition.get('severity')}")
        if not str(definition.get("manual_fix") or "").strip():
            errors.append(f"{issue_type}: manual_fix vide")
    return errors
